MyProject: math::Matrix< T > Class Template Reference
math::Matrix< T > Class Template Reference
Template class representing a mathematical matrix.
#include <Matrix.hpp>
Public Member Functions
Matrix (const size_t rows, const size_t cols)
Construct a matrix with given rows and columns.
Matrix ()
Default constructor initializing an empty matrix.
math::Vector3D apply (const math::Vector3D &vectorToApply, const bool isInverse)
Applies the matrix or its inverse to a 3D vector.
T & operator() (const size_t row, const size_t col)
Access or modify an element at a given row and column.
void operator+= (Matrix< T > &other)
Add another matrix to this matrix (element-wise).
void operator-= (Matrix< T > &other)
Subtract another matrix from this matrix (element-wise).
void operator*= (Matrix< T > &other)
Multiply this matrix by another matrix.
void operator*= (T coef)
Multiply all elements of this matrix by a scalar coefficient.
Matrix< T > & operator= (Matrix< T > other)
Assignment operator.
Matrix< T > & operator= (const initializer_list< initializer_list< T > > &list)
Assign matrix values from an initializer list.
size_t getNbRows () const
Get number of rows.
size_t getNbCols () const
Get number of columns.
void displayMatrix ()
Display the matrix elements with their indices.
Private Member Functions
void checkSameSize (const Matrix< T > &other) const
Check if another matrix has the same size.
void createMatrice ()
Initialize the matrix with zeros.
void createInverseMatrice ()
Initialize the inverse matrix with zeros.
void setMatrixIdentity ()
Set the matrix to identity (only if square).
void setMatrixInverseIndentity ()
Set the inverse matrix to identity (only if square).
vector< vector< T > > createMatrixExtern (size_t rows, size_t cols)
Create an external matrix with given dimensions, initialized to zero.
void inverse ()
Compute the inverse of the matrix using Gaussian elimination.
Private Attributes
vector< vector< T > > mMatrix = vector<vector<T>>()
vector< vector< T > > mInverseMatrix = vector<vector<T>>()
size_t mRows
size_t mCols
Detailed Description
template<typename T>
class math::Matrix< T >
Template class representing a mathematical matrix.
Template Parameters
T Type of the elements stored in the matrix (e.g. float, double).
Definition at line 32 of file Matrix.hpp.
Constructor & Destructor Documentation
Matrix() [1/2]
template<typename T > math::Matrix< T >::Matrix (const size_t rows, const size_t cols) inline
Construct a matrix with given rows and columns.
Initializes the matrix, its inverse, sets the inverse matrix to identity, and computes the inverse.
Parameters
rows Number of rows.
cols Number of columns.
Definition at line 42 of file Matrix.hpp.
            : mRows(rows), mCols(cols) {
            createMatrice();
            createInverseMatrice();
            setMatrixInverseIndentity();
            inverse();
        };
References math::Matrix< T >::createInverseMatrice(), math::Matrix< T >::createMatrice(), math::Matrix< T >::inverse(), and math::Matrix< T >::setMatrixInverseIndentity().
Matrix() [2/2]
template<typename T > math::Matrix< T >::Matrix () inline
Default constructor initializing an empty matrix.
Definition at line 53 of file Matrix.hpp.
: mRows(0), mCols(0) {};
Member Function Documentation
apply()
template<typename T > math::Vector3D math::Matrix< T >::apply (const math::Vector3D & vectorToApply, const bool isInverse)
Applies the matrix or its inverse to a 3D vector.
Parameters
vectorToApply Vector3D to be transformed.
isInverse If true, applies the inverse matrix; otherwise applies the matrix.
Returns
Transformed Vector3D.
checkSameSize()
template<typename T > void math::Matrix< T >::checkSameSize (const Matrix< T > & other) const private
Check if another matrix has the same size.
Throws raytracer::MatrixError if sizes differ.
Parameters
other Matrix to compare.
createInverseMatrice()
template<typename T > void math::Matrix< T >::createInverseMatrice () private
Initialize the inverse matrix with zeros.
Referenced by math::Matrix< T >::Matrix().
createMatrice()
template<typename T > void math::Matrix< T >::createMatrice () private
Initialize the matrix with zeros.
Referenced by math::Matrix< T >::Matrix().
createMatrixExtern()
template<typename T > vector< vector< T > > math::Matrix< T >::createMatrixExtern (size_t rows, size_t cols) private
Create an external matrix with given dimensions, initialized to zero.
Parameters
rows Number of rows.
cols Number of columns.
Returns
New zero-initialized matrix.
displayMatrix()
template<typename T > void math::Matrix< T >::displayMatrix ()
Display the matrix elements with their indices.
getNbCols()
template<typename T > size_t math::Matrix< T >::getNbCols () const inline
Get number of columns.
Returns
Number of columns.
Definition at line 135 of file Matrix.hpp.
{ return mCols; };
References math::Matrix< T >::mCols.
getNbRows()
template<typename T > size_t math::Matrix< T >::getNbRows () const inline
Get number of rows.
Returns
Number of rows.
Definition at line 129 of file Matrix.hpp.
{ return mRows; };
References math::Matrix< T >::mRows.
inverse()
template<typename T > void math::Matrix< T >::inverse () private
Compute the inverse of the matrix using Gaussian elimination.
Assumes the matrix is square and invertible.
Referenced by math::Matrix< T >::Matrix().
operator()()
template<typename T > T & math::Matrix< T >::operator() (const size_t row, const size_t col)
Access or modify an element at a given row and column.
Throws raytracer::MatrixError if indices are out of bounds.
Parameters
row Row index.
col Column index.
Returns
Reference to the element at (row, col).
operator*=() [1/2]
template<typename T > void math::Matrix< T >::operator*= (Matrix< T > & other)
Multiply this matrix by another matrix.
Throws raytracer::MatrixError if sizes are incompatible.
Parameters
other Matrix to multiply with.
operator*=() [2/2]
template<typename T > void math::Matrix< T >::operator*= (T coef)
Multiply all elements of this matrix by a scalar coefficient.
Parameters
coef Scalar coefficient.
operator+=()
template<typename T > void math::Matrix< T >::operator+= (Matrix< T > & other)
Add another matrix to this matrix (element-wise).
Parameters
other Matrix to add.
operator-=()
template<typename T > void math::Matrix< T >::operator-= (Matrix< T > & other)
Subtract another matrix from this matrix (element-wise).
Parameters
other Matrix to subtract.
operator=() [1/2]
template<typename T > Matrix< T > & math::Matrix< T >::operator= (const initializer_list< initializer_list< T > > & list)
Assign matrix values from an initializer list.
If the matrix is empty, resizes it to fit the initializer list.
Parameters
list Nested initializer list representing matrix values.
Returns
Reference to this matrix.
operator=() [2/2]
template<typename T > Matrix< T > & math::Matrix< T >::operator= (Matrix< T > other)
Assignment operator.
Swaps data with another matrix.
Parameters
other Matrix to assign.
Returns
Reference to this matrix.
setMatrixIdentity()
template<typename T > void math::Matrix< T >::setMatrixIdentity () private
Set the matrix to identity (only if square).
setMatrixInverseIndentity()
template<typename T > void math::Matrix< T >::setMatrixInverseIndentity () private
Set the inverse matrix to identity (only if square).
Referenced by math::Matrix< T >::Matrix().
Member Data Documentation
mCols
template<typename T > size_t math::Matrix< T >::mCols private
Number of columns
Definition at line 146 of file Matrix.hpp.
Referenced by math::Matrix< T >::getNbCols().
mInverseMatrix
template<typename T > vector<vector<T> > math::Matrix< T >::mInverseMatrix = vector<vector<T>>() private
Inverse matrix data
Definition at line 144 of file Matrix.hpp.
mMatrix
template<typename T > vector<vector<T> > math::Matrix< T >::mMatrix = vector<vector<T>>() private
Matrix data
Definition at line 143 of file Matrix.hpp.
mRows
template<typename T > size_t math::Matrix< T >::mRows private
Number of rows
Definition at line 145 of file Matrix.hpp.
Referenced by math::Matrix< T >::getNbRows().
The documentation for this class was generated from the following file:
src/core/math/Matrix.hpp