MyProject: raytracer::World Class Reference
raytracer::World Class Reference
#include <World.hpp>
Public Member Functions
World ()=default
~World ()=default
double getDistance (const math::Point3D borigin, const math::Point3D &intersectionPoint) const
double hit (const Ray &r, const vector< std::unique_ptr< IPrimitive > > &primitives) const
Detailed Description
Definition at line 17 of file World.hpp.
Constructor & Destructor Documentation
World()
raytracer::World::World () default
~World()
raytracer::World::~World () default
Member Function Documentation
getDistance()
double raytracer::World::getDistance (const math::Point3D borigin, const math::Point3D & intersectionPoint) const inline
Definition at line 22 of file World.hpp.
{
            const double distance = (borigin - intersectionPoint).length();
            const double attenuation = 1.0 / distance;
            return attenuation;
        }
Referenced by raytracer::DirectionalLight::getColorShadow(), and raytracer::PointLight::getColorShadow().
hit()
double raytracer::World::hit (const Ray & r, const vector< std::unique_ptr< IPrimitive > > & primitives) const inline
Definition at line 29 of file World.hpp.
{
            double closest = std::numeric_limits<double>::max();
            double hitResult = 0.0;
            for (const auto &obj : primitives) {
                hitResult = obj.get()->hits(r);
                if (hitResult > 0.0 && hitResult < closest)
                    closest = hitResult;
            }
            return closest;
        }
Referenced by raytracer::DirectionalLight::getColorShadow(), and raytracer::PointLight::getColorShadow().
The documentation for this class was generated from the following file:
src/core/helpers/World.hpp