MyProject: raytracer::Plane Class Reference
raytracer::Plane Class Reference
Représente un plan dans la scène de raytracing.
#include <Plane.hpp>
Public Member Functions
Plane ()=default
Constructeur par défaut.
Plane (const string &axis, const int position, const Color &color, const map< string, math::Matrix< double > > &allMatrix, const math::Vector3D vectorRatation)
Constructeur paramétré du plan.
double hits (const Ray &ray) override
Calcule l'intersection entre un rayon et le plan.
double checkRayPlaneIntersection (const Ray &ray, const math::Point3D &position) const
Vérifie l'intersection entre un rayon et un plan défini par un point.
math::Vector3D getNormal (const math::Point3D &point) const override
Retourne la normale du plan à un point donné.
Public Member Functions inherited from raytracer::IPrimitive
IPrimitive ()=default
Constructeur par défaut.
virtual ~IPrimitive ()=default
Destructeur virtuel par défaut.
virtual double hits (const Ray &ray)=0
Méthode virtuelle pure pour tester l'intersection entre la primitive et un rayon.
virtual math::Vector3D getNormal (const math::Point3D &point) const =0
Méthode virtuelle pure pour obtenir la normale à la surface de la primitive à un point donné.
Public Attributes
string mAxis = "Z"
Axe du plan ("X", "Y" ou "Z").
int mPosition = 0
Position du plan sur l’axe sélectionné.
Color mColor
Couleur du plan.
map< string, math::Matrix< double > > mAllMatrix
Ensemble des matrices de transformation appliquées.
math::Vector3D mVectorRotation
Vecteur représentant la rotation du plan.
Public Attributes inherited from raytracer::IPrimitive
Color mBaseColor
Couleur de la primitive.
math::Point3D mBaseCenter
Centre ou point de référence de la primitive.
int mBaseRadius
Rayon (pour les sphères ou cylindres)
string mBaseAxis
Axe principal (pour les plans)
int mBasePosition
Position selon l'axe (pour les plans)
int mBaseHeight
Hauteur (pour les cylindres)
map< string, math::Matrix< double > > mBaseAllMatrix
Matrices de transformation (rotation, translation, etc.)
math::Vector3D mBaseRotation
Vecteur de rotation selon les axes X, Y, Z.
Detailed Description
Représente un plan dans la scène de raytracing.
Cette classe hérite de IPrimitive et permet de calculer les intersections entre un rayon et un plan orienté selon un axe (X, Y ou Z).
Definition at line 23 of file Plane.hpp.
Constructor & Destructor Documentation
Plane() [1/2]
raytracer::Plane::Plane () default
Constructeur par défaut.
Plane() [2/2]
raytracer::Plane::Plane (const string & axis, const int position, const Color & color, const map< string, math::Matrix< double > > & allMatrix, const math::Vector3D vectorRatation) inline
Constructeur paramétré du plan.
Parameters
axis Axe de base du plan ("X", "Y" ou "Z").
position Position du plan sur l'axe donné.
color Couleur du plan.
allMatrix Matrices de transformations associées.
vectorRatation Vecteur de rotation appliqué au plan.
Definition at line 39 of file Plane.hpp.
                : mAxis(axis), mPosition(position), mColor(color),
                mAllMatrix(allMatrix), mVectorRotation(vectorRatation) {}
Member Function Documentation
checkRayPlaneIntersection()
double raytracer::Plane::checkRayPlaneIntersection (const Ray & ray, const math::Point3D & position) const
Vérifie l'intersection entre un rayon et un plan défini par un point.
Vérifie l'intersection entre un rayon et un plan donné par un point.
Parameters
ray Le rayon à tester.
position Un point appartenant au plan.
Returns
Distance t de l'intersection, ou -1.0 si pas d'intersection.
Utilise la formule de l’intersection entre un rayon et un plan.
Parameters
ray Le rayon à tester.
position Un point appartenant au plan.
Returns
La distance t à l'intersection, ou -1.0 s'il n'y a pas d'intersection.
Definition at line 46 of file Plane.cpp.
{
    const math::Vector3D normal = getNormal(position);
    const double epsilon = 1e-10;
    const double rayPlaneAngle = ray.mDirection.dot(normal);
    const math::Vector3D pointOnPlane = position - ray.mOrigin;
    const double t = pointOnPlane.dot(normal) / rayPlaneAngle;
    if (abs(rayPlaneAngle) < epsilon) {
        // Le rayon est parallèle au plan
        return -1.0;
    }
    return t;
}
References math::Vector3D::dot(), raytracer::Ray::mDirection, and raytracer::Ray::mOrigin.
Referenced by hits().
getNormal()
math::Vector3D raytracer::Plane::getNormal (const math::Point3D & point) const override virtual
Retourne la normale du plan à un point donné.
Retourne la normale du plan en un point donné.
Parameters
point Le point sur le plan (inutile ici car la normale est constante).
Returns
Le vecteur normal au plan.
Cette fonction retourne un vecteur normal au plan en fonction de son orientation (axe de base).
Parameters
point Le point sur le plan (non utilisé ici).
Returns
Le vecteur normal unitaire du plan.
Implements raytracer::IPrimitive.
Definition at line 70 of file Plane.cpp.
{
    (void)point;  // Le point est ignoré, car la normale est constante.
    if (mBaseAxis == "X") {
        return math::Vector3D(1.0, 0.0, 0.0);
    }
    if (mBaseAxis == "Y") {
        return math::Vector3D(0.0, 0.0, 1.0);
    }
    if (mBaseAxis == "Z") {
        return math::Vector3D(0.0, 1.0, 0.0);
    }
    return math::Vector3D(0.0, 0.0, 0.0);  // Valeur par défaut en cas d'erreur
}
hits()
double raytracer::Plane::hits (const Ray & ray) override virtual
Calcule l'intersection entre un rayon et le plan.
Parameters
ray Le rayon à tester.
Returns
Distance t entre l'origine du rayon et le point d'intersection, ou -1.0 si aucune intersection.
Cette méthode détermine si un rayon intersecte le plan en fonction de l'axe de base (mBaseAxis) et de la position sur cet axe (mBasePosition).
Parameters
ray Le rayon à tester.
Returns
La distance t à l'intersection, ou -1.0 s'il n'y a pas d'intersection.
Implements raytracer::IPrimitive.
Definition at line 21 of file Plane.cpp.
{
    math::Point3D position;
    if (mBaseAxis == "X") {
        position = math::Point3D(mBasePosition, 0.0, 0.0);
    } else if (mBaseAxis == "Y") {
        position = math::Point3D(0.0, 0.0, mBasePosition);
    } else if (mBaseAxis == "Z") {
        position = math::Point3D(0.0, mBasePosition, 0.0);
    } else {
        return -1.0;
    }
    return checkRayPlaneIntersection(ray, position);
}
References checkRayPlaneIntersection(), raytracer::IPrimitive::mBaseAxis, and raytracer::IPrimitive::mBasePosition.
Member Data Documentation
mAllMatrix
map<string, math::Matrix<double> > raytracer::Plane::mAllMatrix
Ensemble des matrices de transformation appliquées.
Definition at line 81 of file Plane.hpp.
mAxis
string raytracer::Plane::mAxis = "Z"
Axe du plan ("X", "Y" ou "Z").
Definition at line 72 of file Plane.hpp.
mColor
Color raytracer::Plane::mColor
Couleur du plan.
Definition at line 78 of file Plane.hpp.
mPosition
int raytracer::Plane::mPosition = 0
Position du plan sur l’axe sélectionné.
Definition at line 75 of file Plane.hpp.
mVectorRotation
math::Vector3D raytracer::Plane::mVectorRotation
Vecteur représentant la rotation du plan.
Definition at line 84 of file Plane.hpp.
The documentation for this class was generated from the following files:
src/primitives/plane/Plane.hpp
src/primitives/plane/Plane.cpp