MyProject: raytracer::Scene Class Reference
raytracer::Scene Class Reference
Classe représentant une scène 3D pour le ray tracing.
#include <Scene.hpp>
Public Member Functions
Scene ()=default
Constructeur par défaut.
~Scene ()=default
Destructeur par défaut.
void render (Image &image)
Lance le rendu de la scène dans l'image fournie.
void init (const core::Parser &sceneParser)
Initialise la scène à partir d'un parser de fichier de scène.
void initPlanes (const vector< Plane > &planes, const size_t o, Factory &factory)
Initialise les plans dans la scène.
void initSpheres (const vector< Sphere > &spheres, const size_t o, Factory &factory)
Initialise les sphères dans la scène.
void initCylinders (const vector< Cylinder > &cylinders, const size_t o, Factory &factory)
Initialise les cylindres dans la scène.
void initCones (const vector< Cone > &cones, const size_t o, Factory &factory)
Initialise les cônes dans la scène.
void initPoints (const vector< PointLight > &points, const size_t o, Factory &factory)
Initialise les sources lumineuses ponctuelles dans la scène.
void initDirectionals (const vector< DirectionalLight > &directionals, const size_t o, Factory &factory)
Initialise les sources lumineuses directionnelles dans la scène.
Color getColor (const unsigned int x, const unsigned int y, const unsigned int height, const unsigned int width)
Calcule la couleur d'un pixel donné dans l'image.
Color getLightColor (const IPrimitive &primitive, const math::Point3D &intersectionPoint, const math::Vector3D &normal)
Calcule la couleur de la lumière sur une primitive à un point d'intersection donné.
void addPlane (const Plane &plane)
void addSphere (const Sphere &sphere)
void addLight (const ILigths &light)
void setCamera (const Camera &camera)
void addAmbientLight (AmbientLight &&l)
void addPointLight (PointLight &&l)
void addDirectionalLight (DirectionalLight &&l)
const std::vector< Plane > & getPlanes () const
const std::vector< Sphere > & getSpheres () const
const std::vector< ILigths > & getLights () const
const Camera & getCamera () const
const std::vector< AmbientLight > & getAmbientLights () const
const std::vector< PointLight > & getPointLights () const
const std::vector< DirectionalLight > & getDirectionalLights () const
Public Attributes
Camera _camera
Caméra utilisée pour la scène.
double _ambient = 0.0
Coefficient d'éclairage ambiant.
double _diffuse = 0.0
Coefficient d'éclairage diffus.
vector< unique_ptr< IPrimitive > > _primitives
Vecteur de pointeurs uniques vers les primitives de la scène.
vector< unique_ptr< ILight > > _lights
Vecteur de pointeurs uniques vers les sources lumineuses de la scène.
mt19937 _gen = mt19937(std::random_device()())
Générateur de nombres aléatoires (Mersenne Twister)
uniform_real_distribution< double > _dis
Distribution uniforme de nombres aléatoires entre 0.0 et 1.0.
Private Attributes
std::vector< Plane > planes
std::vector< Sphere > spheres
std::vector< ILigths > lights_
std::vector< AmbientLight > _ambientLights
std::vector< PointLight > _pointLights
std::vector< DirectionalLight > _directionalLights
Camera camera_
Detailed Description
Classe représentant une scène 3D pour le ray tracing.
Cette classe gère les primitives, les lumières, la caméra, et les opérations de rendu pour générer une image.
Definition at line 32 of file Scene.hpp.
Constructor & Destructor Documentation
Scene()
raytracer::Scene::Scene () default
Constructeur par défaut.
~Scene()
raytracer::Scene::~Scene () default
Destructeur par défaut.
Member Function Documentation
addAmbientLight()
void raytracer::Scene::addAmbientLight (AmbientLight && l) inline
Definition at line 46 of file Scene.hpp.
        {
             _ambientLights.push_back(std::move(l));
        }
References _ambientLights.
Referenced by raytracer::Parser::parseLights().
addDirectionalLight()
void raytracer::Scene::addDirectionalLight (DirectionalLight && l) inline
Definition at line 54 of file Scene.hpp.
        {
            _directionalLights.push_back(std::move(l));
        }
References _directionalLights.
Referenced by raytracer::Parser::parseLights().
addLight()
void raytracer::Scene::addLight (const ILigths & light) inline
Definition at line 40 of file Scene.hpp.
{
            lights_.push_back(light);
        }
References lights_.
addPlane()
void raytracer::Scene::addPlane (const Plane & plane) inline
Definition at line 34 of file Scene.hpp.
{
            planes.push_back(plane);
        }
References planes.
Referenced by raytracer::Parser::parse().
addPointLight()
void raytracer::Scene::addPointLight (PointLight && l) inline
Definition at line 50 of file Scene.hpp.
        {
             _pointLights.push_back(std::move(l));
        }
References _pointLights.
Referenced by raytracer::Parser::parseLights().
addSphere()
void raytracer::Scene::addSphere (const Sphere & sphere) inline
Definition at line 37 of file Scene.hpp.
{
            spheres.push_back(sphere);
        }
References spheres.
Referenced by raytracer::Parser::parse().
getAmbientLights()
const std::vector< AmbientLight > & raytracer::Scene::getAmbientLights () const inline
Definition at line 63 of file Scene.hpp.
{ return _ambientLights;}
References _ambientLights.
getCamera()
const Camera & raytracer::Scene::getCamera () const inline
Definition at line 62 of file Scene.hpp.
{ return camera_; }
References camera_.
getColor()
Color raytracer::Scene::getColor (const unsigned int x, const unsigned int y, const unsigned int height, const unsigned int width)
Calcule la couleur d'un pixel donné dans l'image.
Computes the color of a pixel at coordinates (x, y) using ray tracing.
Parameters
x Coordonnée horizontale du pixel.
y Coordonnée verticale du pixel.
height Hauteur totale de l'image.
width Largeur totale de l'image.
Returns
Color Couleur calculée du pixel.
Parameters
x Horizontal pixel coordinate.
y Vertical pixel coordinate.
height Height of the image.
width Width of the image.
Returns
Color The computed color of the pixel.
< Initialize color to black
< Generate ray through pixel
< Initialize closest hit distance
< Initialize closest primitive index
< Compute intersection point
< Compute surface normal
< Calculate lighting at intersection
< Clamp the final color
Definition at line 63 of file Scene.cpp.
{
    Color color(0.0, 0.0, 0.0);
    math::Point3D intersectionPoint;
    math::Vector3D normal;
    const size_t nbPrimitives = _primitives.size();
    double hitResult = 0.0;
    double u = 0.0;
    double v = 0.0;
    // Compute normalized pixel coordinates with jitter for anti-aliasing
    u = (static_cast<double>(x) + _dis(_gen)) / width;
    v = (static_cast<double>(y) + _dis(_gen)) / height;
    raytracer::Ray r = _camera.ray(u, v);
    double closestHit = numeric_limits<double>::max();
    size_t closestPrimitiveIndex = numeric_limits<size_t>::max();
    // Find closest intersected primitive
    for (size_t j = 0; j < nbPrimitives; j++) {
        hitResult = _primitives[j].get()->hits(r);
        if ((hitResult > 0.0) && (hitResult < closestHit)) {
            closestHit = hitResult;
            closestPrimitiveIndex = j;
        }
    }
    if (closestPrimitiveIndex != numeric_limits<size_t>::max()) {
        intersectionPoint = r.mOrigin + (r.mDirection * closestHit);
        normal = math::Vector3D::normalize(
            _primitives[closestPrimitiveIndex].get()->getNormal(intersectionPoint));
        color += getLightColor(
            *_primitives[closestPrimitiveIndex],
            intersectionPoint, normal);
    }
    color.clamp();
    return color;
}
References _camera, _dis, _gen, _primitives, raytracer::Color::clamp(), getLightColor(), raytracer::Ray::mDirection, raytracer::Ray::mOrigin, math::Vector3D::normalize(), and raytracer::Camera::ray().
Referenced by render().
getDirectionalLights()
const std::vector< DirectionalLight > & raytracer::Scene::getDirectionalLights () const inline
Definition at line 65 of file Scene.hpp.
{ return _directionalLights;}
References _directionalLights.
getLightColor()
Color raytracer::Scene::getLightColor (const IPrimitive & primitive, const math::Point3D & intersectionPoint, const math::Vector3D & normal)
Calcule la couleur de la lumière sur une primitive à un point d'intersection donné.
Calculate the color contribution of the lights on a primitive at an intersection point.
Parameters
primitive La primitive à éclairer.
intersectionPoint Point d'intersection sur la primitive.
normal Normale à la surface au point d'intersection.
Returns
Color Couleur résultante avec éclairage.
Parameters
primitive The primitive being shaded.
intersectionPoint The point on the primitive where the ray hit.
normal The surface normal at the intersection point.
Returns
Color The resulting color including ambient and diffuse lighting.
< Start with ambient lighting
< Calculate angle between light direction and normal
< Skip light if it's behind the surface
< Compute shadow attenuation
< Add diffuse component
< Clamp color values to valid range
Definition at line 29 of file Scene.cpp.
{
    Color color = primitive.mBaseColor * _ambient;
    Color attenuation;
    double angle = 0.0;
    for (const auto &light : _lights) {
        angle = normal.dot(math::Vector3D::normalize(
            light.get()->mBaseOrigin - intersectionPoint));
        if (angle <= 0.0)
            continue;
        attenuation = light.get()->getColorShadow(intersectionPoint, normal, _primitives);
        color += (attenuation * angle * primitive.mBaseColor * _diffuse);
    }
    color.clamp();
    return color;
}
References _ambient, _diffuse, _lights, _primitives, raytracer::Color::clamp(), math::Vector3D::dot(), raytracer::IPrimitive::mBaseColor, and math::Vector3D::normalize().
Referenced by getColor().
getLights()
const std::vector< ILigths > & raytracer::Scene::getLights () const inline
Definition at line 61 of file Scene.hpp.
{ return lights_; }
References lights_.
getPlanes()
const std::vector< Plane > & raytracer::Scene::getPlanes () const inline
Definition at line 59 of file Scene.hpp.
{ return planes; }
References planes.
getPointLights()
const std::vector< PointLight > & raytracer::Scene::getPointLights () const inline
Definition at line 64 of file Scene.hpp.
{ return _pointLights;}
References _pointLights.
getSpheres()
const std::vector< Sphere > & raytracer::Scene::getSpheres () const inline
Definition at line 60 of file Scene.hpp.
{ return spheres; }
References spheres.
init()
void raytracer::Scene::init (const core::Parser & sceneParser)
Initialise la scène à partir d'un parser de fichier de scène.
Parameters
sceneParser Objet Parser contenant les données de la scène.
Referenced by core::RayTracer::run().
initCones()
void raytracer::Scene::initCones (const vector< Cone > & cones, const size_t o, Factory & factory)
Initialise les cônes dans la scène.
Parameters
cones Vecteur de cônes à initialiser.
o Offset dans le vecteur des primitives.
factory Usine de création des primitives.
initCylinders()
void raytracer::Scene::initCylinders (const vector< Cylinder > & cylinders, const size_t o, Factory & factory)
Initialise les cylindres dans la scène.
Parameters
cylinders Vecteur de cylindres à initialiser.
o Offset dans le vecteur des primitives.
factory Usine de création des primitives.
initDirectionals()
void raytracer::Scene::initDirectionals (const vector< DirectionalLight > & directionals, const size_t o, Factory & factory)
Initialise les sources lumineuses directionnelles dans la scène.
Parameters
directionals Vecteur de lumières directionnelles à initialiser.
o Offset dans le vecteur des lumières.
factory Usine de création des lumières.
initPlanes()
void raytracer::Scene::initPlanes (const vector< Plane > & planes, const size_t offset, Factory & factory)
Initialise les plans dans la scène.
Initialize plane primitives in the scene.
Parameters
planes Vecteur de plans à initialiser.
o Offset dans le vecteur des primitives.
factory Usine de création des primitives.
Parameters
planes Vector of Plane objects to initialize.
offset Offset in _primitives vector to place planes.
factory Factory object to create primitives.
Definition at line 133 of file Scene.cpp.
{
    const size_t nbPlanes = planes.size();
    map<string, math::Matrix<double>> matrix;
    double transformation = 0.0;
    for (size_t i = 0; i < nbPlanes; i++) {
        transformation = 0.0;
        _primitives.push_back(factory.createPrimitive(Factory::PrimitiveType::PLANE));
        _primitives[i + offset].get()->mBaseColor = planes[i].mColor;
        matrix = planes[i].mAllMatrix;
        if (planes[i].mAllMatrix.count("translation") > 0)
            transformation = matrix["translation"](0, 1);
        _primitives[i + offset].get()->mBasePosition =
            static_cast<int>(planes[i].mPosition + transformation);
        _primitives[i + offset].get()->mBaseAxis = planes[i].mAxis;
        _primitives[i + offset].get()->mBaseAllMatrix = planes[i].mAllMatrix;
        _primitives[i + offset].get()->mBaseRotation = planes[i].mVectorRotation;
    }
}
References _primitives, raytracer::Factory::createPrimitive(), raytracer::Factory::PLANE, and planes.
initPoints()
void raytracer::Scene::initPoints (const vector< PointLight > & points, const size_t o, Factory & factory)
Initialise les sources lumineuses ponctuelles dans la scène.
Parameters
points Vecteur de lumières ponctuelles à initialiser.
o Offset dans le vecteur des lumières.
factory Usine de création des lumières.
initSpheres()
void raytracer::Scene::initSpheres (const vector< Sphere > & spheres, const size_t offset, Factory & factory)
Initialise les sphères dans la scène.
Initialize sphere primitives in the scene.
Parameters
spheres Vecteur de sphères à initialiser.
o Offset dans le vecteur des primitives.
factory Usine de création des primitives.
Parameters
spheres Vector of Sphere objects to initialize.
offset Offset in _primitives vector to place spheres.
factory Factory object to create primitives.
Definition at line 162 of file Scene.cpp.
{
    const size_t nbSpheres = spheres.size();
    map<string, math::Matrix<double>> matrix;
    for (size_t i = 0; i < nbSpheres; i++) {
        _primitives.push_back(factory.createPrimitive(Factory::PrimitiveType::SPHERE));
        if (spheres[i].mAllMatrix.count("translation") > 0) {
            matrix = spheres[i].mAllMatrix;
            _primitives[i + offset].get()->mBaseCenter = math::Point3D(
                spheres[i].mX + matrix["translation"](0, 3),
                spheres[i].mY + matrix["translation"](1, 3),
                spheres[i].mZ + matrix["translation"](2, 3));
        } else {
            _primitives[i + offset].get()->mBaseCenter = math::Point3D(
                spheres[i].mX, spheres[i].mY, spheres[i].mZ);
        }
        _primitives[i + offset].get()->mBaseColor = spheres[i].mColor;
        _primitives[i + offset].get()->mBaseRadius = spheres[i].mRadius;
        _primitives[i + offset].get()->mBaseAllMatrix = spheres[i].mAllMatrix;
        _primitives[i + offset].get()->mBaseRotation = spheres[i].mVectorRotation;
    }
}
References _primitives, raytracer::Factory::createPrimitive(), raytracer::Factory::SPHERE, and spheres.
render()
void raytracer::Scene::render (raytracer::Image & image)
Lance le rendu de la scène dans l'image fournie.
Render the entire scene to an image.
Parameters
image Référence à l'objet Image dans lequel le rendu sera effectué.
Parameters
image The image to render to.
< Set pixel color in image
Definition at line 112 of file Scene.cpp.
{
    raytracer::Color color;
    const unsigned int height = image.getHeight();
    const unsigned int width = image.getWidth();
    for (unsigned int y = 0; y < height; y++) {
        for (unsigned int x = 0; x < width; x++) {
            color = getColor(x, y, height, width);
            image.setPixel(x, y, color);
        }
    }
}
References getColor(), raytracer::Image::getHeight(), raytracer::Image::getWidth(), and raytracer::Image::setPixel().
Referenced by core::RayTracer::run().
setCamera()
void raytracer::Scene::setCamera (const Camera & camera) inline
Definition at line 43 of file Scene.hpp.
{
            camera_ = camera;
        }
References camera_.
Referenced by raytracer::Parser::parseCamera().
Member Data Documentation
_ambient
double raytracer::Scene::_ambient = 0.0
Coefficient d'éclairage ambiant.
Definition at line 136 of file Scene.hpp.
Referenced by getLightColor().
_ambientLights
std::vector<AmbientLight> raytracer::Scene::_ambientLights private
Definition at line 28 of file Scene.hpp.
Referenced by addAmbientLight(), and getAmbientLights().
_camera
Camera raytracer::Scene::_camera
Caméra utilisée pour la scène.
Definition at line 133 of file Scene.hpp.
Referenced by getColor(), and core::RayTracer::run().
_diffuse
double raytracer::Scene::_diffuse = 0.0
Coefficient d'éclairage diffus.
Definition at line 139 of file Scene.hpp.
Referenced by getLightColor().
_directionalLights
std::vector<DirectionalLight> raytracer::Scene::_directionalLights private
Definition at line 30 of file Scene.hpp.
Referenced by addDirectionalLight(), and getDirectionalLights().
_dis
uniform_real_distribution<double> raytracer::Scene::_dis
Initial value:
=
            uniform_real_distribution<double>(0.0, 1.0)
Distribution uniforme de nombres aléatoires entre 0.0 et 1.0.
Definition at line 151 of file Scene.hpp.
Referenced by getColor().
_gen
mt19937 raytracer::Scene::_gen = mt19937(std::random_device()())
Générateur de nombres aléatoires (Mersenne Twister)
Definition at line 148 of file Scene.hpp.
Referenced by getColor().
_lights
vector<unique_ptr<ILight> > raytracer::Scene::_lights
Vecteur de pointeurs uniques vers les sources lumineuses de la scène.
Definition at line 145 of file Scene.hpp.
Referenced by getLightColor().
_pointLights
std::vector<PointLight> raytracer::Scene::_pointLights private
Definition at line 29 of file Scene.hpp.
Referenced by addPointLight(), and getPointLights().
_primitives
vector<unique_ptr<IPrimitive> > raytracer::Scene::_primitives
Vecteur de pointeurs uniques vers les primitives de la scène.
Definition at line 142 of file Scene.hpp.
Referenced by getColor(), getLightColor(), initPlanes(), and initSpheres().
camera_
Camera raytracer::Scene::camera_ private
Definition at line 31 of file Scene.hpp.
Referenced by getCamera(), and setCamera().
lights_
std::vector<ILigths> raytracer::Scene::lights_ private
Definition at line 27 of file Scene.hpp.
Referenced by addLight(), and getLights().
planes
std::vector<Plane> raytracer::Scene::planes private
Definition at line 25 of file Scene.hpp.
Referenced by addPlane(), getPlanes(), and initPlanes().
spheres
std::vector<Sphere> raytracer::Scene::spheres private
Definition at line 26 of file Scene.hpp.
Referenced by addSphere(), getSpheres(), and initSpheres().
The documentation for this class was generated from the following files:
src/core/scene/Scene.hpp
paser/Scene.hpp
src/core/scene/Scene.cpp