MyProject: core::RayTracer Class Reference
core::RayTracer Class Reference
Classe principale du moteur de ray tracing.
#include <RayTracer.hpp>
Public Member Functions
RayTracer (const int ac, char **const av)
Constructeur de la classe RayTracer.
~RayTracer ()=default
Destructeur par défaut.
void help () const
Affiche l'aide et les instructions d'utilisation du programme.
int run () const
Lance l'exécution principale du programme.
Private Attributes
int _ac
char ** _av
Detailed Description
Classe principale du moteur de ray tracing.
Cette classe gère le lancement du programme, la lecture des arguments en ligne de commande, l'affichage de l'aide, le parsing de la scène, et le rendu final de l'image.
Definition at line 27 of file RayTracer.hpp.
Constructor & Destructor Documentation
RayTracer()
core::RayTracer::RayTracer (const int ac, char **const av) inline
Constructeur de la classe RayTracer.
Initialise les paramètres d'exécution (arguments argc et argv).
Parameters
ac Nombre d'arguments.
av Tableau des arguments (chaînes de caractères).
Definition at line 37 of file RayTracer.hpp.
            : _ac(ac), _av(av) {}
~RayTracer()
core::RayTracer::~RayTracer () default
Destructeur par défaut.
Member Function Documentation
help()
void core::RayTracer::help () const
Affiche l'aide et les instructions d'utilisation du programme.
Affiche l'aide et les instructions d'utilisation, puis termine le programme.
Cette méthode affiche la syntaxe correcte pour lancer le programme puis termine l'exécution.
Affiche la syntaxe d'appel correcte du programme et quitte avec un code 0.
Definition at line 22 of file RayTracer.cpp.
{
    cout << "USAGE: ./raytracer <SCENE_FILE>\n";
    cout << "\tSCENE_FILE: scene configuration\n";
    exit(0);
}
Referenced by run().
run()
int core::RayTracer::run () const
Lance l'exécution principale du programme.
Exécute le programme principal de ray tracing.
Traite les arguments, charge et parse le fichier scène, initialise la scène, effectue le rendu et affiche ou sauvegarde l'image.
Returns
int Code de retour (0 en succès, autre en erreur).
Traite les arguments en ligne de commande, ouvre et parse le fichier scène, initialise la scène et l'image, puis lance le rendu. Peut afficher soit une fenêtre SFML si l'option -g est passée, soit sauvegarder une image PPM.
Exceptions
raytracer::ArgumentError si aucun fichier scène n'est fourni.
raytracer::ParseError si le fichier scène ne peut pas être ouvert ou parsé.
Returns
int Code de retour du programme (0 en succès, 84 en erreur).
Definition at line 41 of file RayTracer.cpp.
{
    string scenef, bfile, output, arg;
    ifstream file;
    raytracer::Scene scene;
    bool useSFML = false;
    if (_ac < 2)
        help();
    for (int i = 1; i < _ac; i++) {
        arg = _av[i];
        if (arg == "-h") help();
        if (arg == "-g") useSFML = true;
        else scenef = arg;
    }
    if (scenef.empty())
        throw raytracer::ArgumentError("Error: no scene file provided");
    file.open(scenef);
    if (!file.is_open())
        throw raytracer::ParseError("Error: can't open file " + scenef);
    core::Parser parser(scene._camera);
    try {
        parser.parseFile(scenef);
    } catch (const raytracer::ParseError &e) {
        cerr << e.what() << "\n";
        return 84;
    }
    if (!parser.hasBasicElementInFiles())
        return 84;
    raytracer::Image image(
        static_cast<unsigned int>(scene._camera.width),
        static_cast<unsigned int>(scene._camera.height),
        useSFML
    );
    scene.init(parser);
    scene.render(image);
    const std::filesystem::path p(scenef);
    bfile = p.stem().string();
    output = "screenshots/" + bfile + ".ppm";
    if (useSFML)
        image.displaySFML();
    else
        image.displayPPM(output);
    return 0;
}
References _ac, _av, raytracer::Scene::_camera, raytracer::Image::displayPPM(), raytracer::Image::displaySFML(), core::Parser::hasBasicElementInFiles(), raytracer::Camera::height, help(), raytracer::Scene::init(), core::Parser::parseFile(), raytracer::Scene::render(), raytracer::ParseError::what(), and raytracer::Camera::width.
Referenced by main().
Member Data Documentation
_ac
int core::RayTracer::_ac private
Nombre d'arguments reçus en ligne de commande
Definition at line 64 of file RayTracer.hpp.
Referenced by run().
_av
char** core::RayTracer::_av private
Tableau des arguments reçus en ligne de commande
Definition at line 65 of file RayTracer.hpp.
Referenced by run().
The documentation for this class was generated from the following files:
src/core/RayTracer.hpp
src/core/RayTracer.cpp