MyProject: raytracer::DirectionalLight Class Reference
raytracer::DirectionalLight Class Reference
#include <DirectionalLight.hpp>
Public Member Functions
DirectionalLight ()=default
DirectionalLight (const int originX, const int originY, const int originZ, const double dirX, const double dirY, const double dirZ, const Color &color, const map< string, math::Matrix< double > > &allMatrix, const math::Vector3D vectorRotation)
~DirectionalLight () override=default
Color getColorShadow (const math::Point3D &intersectionPoint, const math::Vector3D &normal, const vector< unique_ptr< IPrimitive > > &primitives) override
Calcule la couleur de la lumière en tenant compte des ombres.
Public Member Functions inherited from raytracer::ILight
virtual ~ILight ()=default
Destructeur virtuel par défaut.
virtual Color getColorShadow (const math::Point3D &intersectionPoint, const math::Vector3D &normal, const vector< unique_ptr< IPrimitive > > &primitives)=0
Calcule la couleur de la lumière en tenant compte des ombres.
Public Attributes
math::Vector3D mDirection
math::Point3D mOrigin
Color mColor
map< string, math::Matrix< double > > mAllMatrix
math::Vector3D mVectorRotation
Public Attributes inherited from raytracer::ILight
math::Point3D mBaseOrigin
math::Vector3D mBaseDirection
Color mBaseColor
math::Vector3D mBaseVectorRotation
Detailed Description
Definition at line 17 of file DirectionalLight.hpp.
Constructor & Destructor Documentation
DirectionalLight() [1/2]
raytracer::DirectionalLight::DirectionalLight () default
DirectionalLight() [2/2]
raytracer::DirectionalLight::DirectionalLight (const int originX, const int originY, const int originZ, const double dirX, const double dirY, const double dirZ, const Color & color, const map< string, math::Matrix< double > > & allMatrix, const math::Vector3D vectorRotation) inline
Definition at line 20 of file DirectionalLight.hpp.
                : mDirection(dirX, dirY, dirZ),
                mOrigin(originX, originY, originZ), mColor(color),
                mAllMatrix(allMatrix), mVectorRotation(vectorRotation) {}
~DirectionalLight()
raytracer::DirectionalLight::~DirectionalLight () override default
Member Function Documentation
getColorShadow()
raytracer::Color raytracer::DirectionalLight::getColorShadow (const math::Point3D & intersectionPoint, const math::Vector3D & normal, const vector< unique_ptr< IPrimitive > > & primitives) override virtual
Calcule la couleur de la lumière en tenant compte des ombres.
Cette méthode doit déterminer la contribution lumineuse en fonction du point d'intersection, de la normale à la surface et des primitives présentes dans la scène.
Parameters
intersectionPoint Point d'intersection de la lumière avec une primitive.
normal Normale à la surface au point d'intersection.
primitives Liste des primitives dans la scène.
Returns
Color Couleur résultante tenant compte des ombres.
Implements raytracer::ILight.
Definition at line 12 of file DirectionalLight.cpp.
{
    World world;
    const math::Vector3D lightDir = math::Vector3D::normalize(mBaseDirection);
    const Ray shadowRay(
        intersectionPoint + (normal * 0.01),
        lightDir
    );
    const double closestHit = world.hit(shadowRay, primitives);
    if (closestHit < (mBaseOrigin - intersectionPoint).length()) {
        return Color(0.0, 0.0, 0.0);
    }
    return mBaseColor * world.getDistance(
        mBaseOrigin, intersectionPoint
    );
}
References raytracer::World::getDistance(), raytracer::World::hit(), raytracer::ILight::mBaseColor, raytracer::ILight::mBaseDirection, raytracer::ILight::mBaseOrigin, and math::Vector3D::normalize().
Member Data Documentation
mAllMatrix
map<string, math::Matrix<double> > raytracer::DirectionalLight::mAllMatrix
Definition at line 40 of file DirectionalLight.hpp.
mColor
Color raytracer::DirectionalLight::mColor
Definition at line 39 of file DirectionalLight.hpp.
mDirection
math::Vector3D raytracer::DirectionalLight::mDirection
Definition at line 37 of file DirectionalLight.hpp.
mOrigin
math::Point3D raytracer::DirectionalLight::mOrigin
Definition at line 38 of file DirectionalLight.hpp.
mVectorRotation
math::Vector3D raytracer::DirectionalLight::mVectorRotation
Definition at line 41 of file DirectionalLight.hpp.
The documentation for this class was generated from the following files:
src/lights/directionalLight/DirectionalLight.hpp
src/lights/directionalLight/DirectionalLight.cpp