MyProject: raytracer::Color Class Reference
raytracer::Color Class Reference
#include <Color.hpp>
Public Member Functions
Color ()=default
Color (const double r, const double g, const double b)
~Color ()=default
Color operator* (const int other) const
Color operator* (const double other) const
Color operator* (const Color &other) const
Color & operator/= (const int other)
Color & operator+= (const Color &other)
Color & operator+= (const double other)
Color operator+ (const double other) const
Color operator/ (const int other) const
void clamp ()
double getR () const
double getG () const
double getB () const
Private Attributes
double _r = 0
double _g = 0
double _b = 0
Detailed Description
Definition at line 13 of file Color.hpp.
Constructor & Destructor Documentation
Color() [1/2]
raytracer::Color::Color () default
Referenced by operator*(), operator*(), operator+(), and operator/().
Color() [2/2]
raytracer::Color::Color (const double r, const double g, const double b) inline
Definition at line 16 of file Color.hpp.
                : _r(r), _g(g), _b(b) {}
~Color()
raytracer::Color::~Color () default
Member Function Documentation
clamp()
void raytracer::Color::clamp () inline
Definition at line 57 of file Color.hpp.
            {
                _r = _r < 0.0 ? 0.0 : _r;
                _r = _r > 1.0 ? 1.0 : _r;
                _g = _g < 0.0 ? 0.0 : _g;
                _g = _g > 1.0 ? 1.0 : _g;
                _b = _b < 0.0 ? 0.0 : _b;
                _b = _b > 1.0 ? 1.0 : _b;
            }
References _b, _g, and _r.
Referenced by raytracer::Scene::getColor(), and raytracer::Scene::getLightColor().
getB()
double raytracer::Color::getB () const inline
Definition at line 68 of file Color.hpp.
{ return _b; }
References _b.
Referenced by raytracer::Image::displaySFML(), and operator<<().
getG()
double raytracer::Color::getG () const inline
Definition at line 67 of file Color.hpp.
{ return _g; }
References _g.
Referenced by raytracer::Image::displaySFML(), and operator<<().
getR()
double raytracer::Color::getR () const inline
Definition at line 66 of file Color.hpp.
{ return _r; }
References _r.
Referenced by raytracer::Image::displaySFML(), and operator<<().
operator*() [1/3]
Color raytracer::Color::operator* (const Color & other) const inline
Definition at line 26 of file Color.hpp.
{
                return raytracer::Color(
                    _r * other._r,
                    _g * other._g,
                    _b * other._b
                );
            }
References _b, _g, and _r.
operator*() [2/3]
Color raytracer::Color::operator* (const double other) const inline
Definition at line 23 of file Color.hpp.
{
                return Color(_r * other, _g * other, _b * other);
            }
References _b, _g, _r, and Color().
operator*() [3/3]
Color raytracer::Color::operator* (const int other) const inline
Definition at line 20 of file Color.hpp.
{
                return Color(_r * other, _g * other, _b * other);
            }
References _b, _g, _r, and Color().
operator+()
Color raytracer::Color::operator+ (const double other) const inline
Definition at line 51 of file Color.hpp.
{
                return Color(_r + other, _g + other, _b + other);
            }
References _b, _g, _r, and Color().
operator+=() [1/2]
Color & raytracer::Color::operator+= (const Color & other) inline
Definition at line 39 of file Color.hpp.
{
                _r += other._r;
                _g += other._g;
                _b += other._b;
                return *this;
            }
References _b, _g, and _r.
operator+=() [2/2]
Color & raytracer::Color::operator+= (const double other) inline
Definition at line 45 of file Color.hpp.
{
                _r = _r + other;
                _g = _g + other;
                _b = _b + other;
                return *this;
            }
References _b, _g, and _r.
operator/()
Color raytracer::Color::operator/ (const int other) const inline
Definition at line 54 of file Color.hpp.
{
                return Color(_r / other, _g / other, _b / other);
            }
References _b, _g, _r, and Color().
operator/=()
Color & raytracer::Color::operator/= (const int other) inline
Definition at line 33 of file Color.hpp.
{
                _r /= other;
                _g /= other;
                _b /= other;
                return *this;
            }
References _b, _g, and _r.
Member Data Documentation
_b
double raytracer::Color::_b = 0 private
Definition at line 73 of file Color.hpp.
Referenced by clamp(), getB(), operator*(), operator*(), operator*(), operator+(), operator+=(), operator+=(), operator/(), and operator/=().
_g
double raytracer::Color::_g = 0 private
Definition at line 72 of file Color.hpp.
Referenced by clamp(), getG(), operator*(), operator*(), operator*(), operator+(), operator+=(), operator+=(), operator/(), and operator/=().
_r
double raytracer::Color::_r = 0 private
Definition at line 71 of file Color.hpp.
Referenced by clamp(), getR(), operator*(), operator*(), operator*(), operator+(), operator+=(), operator+=(), operator/(), and operator/=().
The documentation for this class was generated from the following file:
src/core/helpers/Color.hpp