MyProject: raytracer::Image Class Reference
raytracer::Image Class Reference
Classe représentant une image 2D pouvant être affichée via SFML ou exportée en PPM.
#include <Image.hpp>
Public Member Functions
Image (const unsigned int width, const unsigned int height, const bool useSFML)
Constructeur qui initialise une image avec une largeur, une hauteur et un choix d'utilisation de SFML.
~Image ()=default
Destructeur par défaut.
unique_ptr< sf::RenderWindow > initializeWindow (const unsigned int width, const unsigned int height, const bool useSFML)
Initialise la fenêtre SFML si demandée.
void setPixel (const unsigned int x, const unsigned int y, const Color &color)
Définit la couleur d'un pixel à une position donnée.
void displayPPM (const string &filepath)
Exporte l'image au format PPM dans un fichier.
void displaySFML ()
Affiche l'image dans la fenêtre SFML.
unsigned int getWidth () const
Getter pour la largeur de l'image.
unsigned int getHeight () const
Getter pour la hauteur de l'image.
Private Attributes
unsigned int _width
Largeur de l'image.
unsigned int _height
Hauteur de l'image.
map< tuple< int, int >, Color > _pixels
Stockage des pixels par coordonnée.
std::unique_ptr< sf::RenderWindow > _window
Fenêtre SFML pour l'affichage.
sf::Texture mTexture
Texture SFML utilisée pour l'affichage.
sf::Sprite mSprite
Sprite SFML utilisé pour afficher la texture.
Detailed Description
Classe représentant une image 2D pouvant être affichée via SFML ou exportée en PPM.
Cette classe gère la création d'une fenêtre SFML, la modification des pixels, et l'affichage ou l'export au format PPM.
Definition at line 31 of file Image.hpp.
Constructor & Destructor Documentation
Image()
raytracer::Image::Image (const unsigned int width, const unsigned int height, const bool useSFML) inline
Constructeur qui initialise une image avec une largeur, une hauteur et un choix d'utilisation de SFML.
Parameters
width Largeur de l'image en pixels.
height Hauteur de l'image en pixels.
useSFML Booléen indiquant si l'affichage SFML est activé.
Definition at line 40 of file Image.hpp.
            : _width(width), _height(height),
            _window(initializeWindow(width, height, useSFML))  {}
~Image()
raytracer::Image::~Image () default
Destructeur par défaut.
Member Function Documentation
displayPPM()
void raytracer::Image::displayPPM (const string & filepath)
Exporte l'image au format PPM dans un fichier.
Parameters
filepath Chemin du fichier de sortie.
Crée les dossiers parents si nécessaire.
Parameters
filepath Chemin du fichier où enregistrer l'image.
Definition at line 70 of file Image.cpp.
 {
     const std::filesystem::path p(filepath);
     if (!std::filesystem::exists(p.parent_path())) {
         std::filesystem::create_directories(p.parent_path());
     }
     ofstream file(filepath, ios::out | ios::trunc);
     if (!file.is_open()) {
         cerr << "Failed to open file: " << filepath << "\n";
         return;
     }
     file << "P3\n" << _width << " " << _height << "\n255\n";
     for (unsigned int y = 0; y < _height; y++) {
         for (unsigned int x = 0; x < _width; x++) {
             file << _pixels[tuple<int, int>{y, x}];
         }
     }
     file.close();
 }
References _height, and _width.
Referenced by core::RayTracer::run().
displaySFML()
void raytracer::Image::displaySFML ()
Affiche l'image dans la fenêtre SFML.
Cette méthode boucle tant que la fenêtre est ouverte.
Transforme les pixels internes en pixels SFML et affiche jusqu'à ce que la fenêtre soit fermée.
Definition at line 96 of file Image.cpp.
 {
     sf::Image image;
     image.create(_width, _height);
     sf::Texture texture;
     sf::Sprite sprite;
     Color color;
     sf::Uint8 red = 0;
     sf::Uint8 green = 0;
     sf::Uint8 blue = 0;
     for (unsigned int y = 0; y < _height; y++) {
         for (unsigned int x = 0; x < _width; x++) {
             color = _pixels[make_pair(y, x)];
             red = static_cast<sf::Uint8>(color.getR() * 255);
             green = static_cast<sf::Uint8>(color.getG() * 255);
             blue = static_cast<sf::Uint8>(color.getB() * 255);
             image.setPixel(x, y, sf::Color(red, green, blue));
         }
         texture.loadFromImage(image);
         sprite.setTexture(texture);
         _window.get()->clear();
         _window.get()->draw(sprite);
         _window.get()->display();
     }
     while (_window.get()->isOpen()) {
         sf::Event event;
         while (_window.get()->pollEvent(event)) {
             if (event.type == sf::Event::Closed)
                 _window.get()->close();
         }
     }
 }
References _height, _pixels, _width, _window, raytracer::Color::getB(), raytracer::Color::getG(), and raytracer::Color::getR().
Referenced by core::RayTracer::run().
getHeight()
unsigned int raytracer::Image::getHeight () const inline
Getter pour la hauteur de l'image.
Returns
unsigned int Hauteur en pixels.
Definition at line 98 of file Image.hpp.
{ return _height; };
References _height.
Referenced by raytracer::Scene::render().
getWidth()
unsigned int raytracer::Image::getWidth () const inline
Getter pour la largeur de l'image.
Returns
unsigned int Largeur en pixels.
Definition at line 91 of file Image.hpp.
{ return _width; };
References _width.
Referenced by raytracer::Scene::render().
initializeWindow()
unique_ptr< sf::RenderWindow > raytracer::Image::initializeWindow (const unsigned int width, const unsigned int height, const bool useSFML)
Initialise la fenêtre SFML si demandée.
Initialise une fenêtre SFML pour l'affichage.
Parameters
width Largeur de la fenêtre.
height Hauteur de la fenêtre.
useSFML Booléen indiquant si la fenêtre doit être créée.
Returns
unique_ptr<sf::RenderWindow> Pointeur vers la fenêtre créée.
Parameters
width Largeur de la fenêtre en pixels.
height Hauteur de la fenêtre en pixels.
useSFML Booléen indiquant si la fenêtre doit être créée.
Returns
unique_ptr<sf::RenderWindow> Pointeur unique vers la fenêtre créée.
Definition at line 38 of file Image.cpp.
   {
     auto window = make_unique<sf::RenderWindow>();
     if (useSFML) {
         window->create(sf::VideoMode(width, height), "Raytracer", 4);
         window->clear(sf::Color::Black);
         window->display();
     }
     return window;
 }
setPixel()
void raytracer::Image::setPixel (const unsigned int x, const unsigned int y, const Color & color)
Définit la couleur d'un pixel à une position donnée.
Définit la couleur d'un pixel donné dans l'image.
Parameters
x Coordonnée X du pixel.
y Coordonnée Y du pixel.
color Couleur à appliquer.
Parameters
x Coordonnée X du pixel.
y Coordonnée Y du pixel.
color Couleur à appliquer au pixel.
Definition at line 57 of file Image.cpp.
 {
     _pixels[tuple<unsigned int, unsigned int>{y, x}] = color;
 }
References _pixels.
Referenced by raytracer::Scene::render().
Member Data Documentation
_height
unsigned int raytracer::Image::_height private
Hauteur de l'image.
Definition at line 102 of file Image.hpp.
Referenced by displayPPM(), displaySFML(), and getHeight().
_pixels
map<tuple<int, int>, Color> raytracer::Image::_pixels private
Stockage des pixels par coordonnée.
Definition at line 103 of file Image.hpp.
Referenced by displaySFML(), and setPixel().
_width
unsigned int raytracer::Image::_width private
Largeur de l'image.
Definition at line 101 of file Image.hpp.
Referenced by displayPPM(), displaySFML(), and getWidth().
_window
std::unique_ptr<sf::RenderWindow> raytracer::Image::_window private
Fenêtre SFML pour l'affichage.
Definition at line 104 of file Image.hpp.
Referenced by displaySFML().
mSprite
sf::Sprite raytracer::Image::mSprite private
Sprite SFML utilisé pour afficher la texture.
Definition at line 106 of file Image.hpp.
mTexture
sf::Texture raytracer::Image::mTexture private
Texture SFML utilisée pour l'affichage.
Definition at line 105 of file Image.hpp.
The documentation for this class was generated from the following files:
src/core/scene/Image.hpp
src/core/scene/Image.cpp