MyProject: math::Vector3D Class Reference
math::Vector3D Class Reference
Représente un vecteur 3D avec des opérations vectorielles de base.
#include <Math.hpp>
Public Member Functions
Vector3D ()=default
Constructeur par défaut. Initialise à (0, 0, 0).
Vector3D (const double ex, const double ey, const double ez)
Constructeur avec initialisation.
~Vector3D ()=default
double length () const
Calcule la norme (longueur) du vecteur.
double dot (const Vector3D &other) const
Calcule le produit scalaire avec un autre vecteur.
Vector3D operator+ (const Vector3D &other) const
Vector3D operator+= (const Vector3D &other)
Vector3D operator- (const Vector3D &other) const
Vector3D operator-= (const Vector3D &other)
Vector3D operator* (const double scalar) const
Vector3D operator* (const Vector3D &other) const
Vector3D operator*= (const Vector3D &other)
Vector3D operator*= (const double scalar)
Vector3D operator/ (const Vector3D &other) const
Vector3D operator/ (const double scalar) const
Vector3D operator/= (const Vector3D &other)
Vector3D operator/= (const double scalar)
Vector3D operator- () const
Renvoie le vecteur opposé (-x, -y, -z).
void normalize ()
Normalise le vecteur actuel (modifie en place).
Static Public Member Functions
static Vector3D normalize (const Vector3D &vector)
Renvoie un vecteur normalisé à partir d'un autre.
Public Attributes
double mX = 0
Composantes X, Y, Z du vecteur.
double mY = 0
double mZ = 0
Detailed Description
Représente un vecteur 3D avec des opérations vectorielles de base.
Definition at line 18 of file Math.hpp.
Constructor & Destructor Documentation
Vector3D() [1/2]
math::Vector3D::Vector3D () default
Constructeur par défaut. Initialise à (0, 0, 0).
Vector3D() [2/2]
math::Vector3D::Vector3D (const double ex, const double ey, const double ez)
Constructeur avec initialisation.
Parameters
ex Coordonnée X.
ey Coordonnée Y.
ez Coordonnée Z.
~Vector3D()
math::Vector3D::~Vector3D () default
Member Function Documentation
dot()
double math::Vector3D::dot (const Vector3D & other) const
Calcule le produit scalaire avec un autre vecteur.
Parameters
other Le vecteur à utiliser pour le produit scalaire.
Returns
Le résultat du produit scalaire.
Referenced by raytracer::Plane::checkRayPlaneIntersection(), raytracer::Scene::getLightColor(), raytracer::Cone::hits(), raytracer::Cylinder::hits(), and raytracer::Sphere::hits().
length()
double math::Vector3D::length () const
Calcule la norme (longueur) du vecteur.
Returns
La longueur du vecteur.
Referenced by raytracer::PointLight::getColorShadow().
normalize() [1/2]
void math::Vector3D::normalize ()
Normalise le vecteur actuel (modifie en place).
Referenced by raytracer::Camera::calculateDirection(), raytracer::Scene::getColor(), raytracer::DirectionalLight::getColorShadow(), raytracer::PointLight::getColorShadow(), raytracer::Scene::getLightColor(), raytracer::Cone::getNormal(), raytracer::Cylinder::getNormal(), and raytracer::Sphere::getNormal().
normalize() [2/2]
static Vector3D math::Vector3D::normalize (const Vector3D & vector) static
Renvoie un vecteur normalisé à partir d'un autre.
Parameters
vector Le vecteur à normaliser.
Returns
Un nouveau vecteur unitaire.
operator*() [1/2]
Vector3D math::Vector3D::operator* (const double scalar) const
operator*() [2/2]
Vector3D math::Vector3D::operator* (const Vector3D & other) const
operator*=() [1/2]
Vector3D math::Vector3D::operator*= (const double scalar)
operator*=() [2/2]
Vector3D math::Vector3D::operator*= (const Vector3D & other)
operator+()
Vector3D math::Vector3D::operator+ (const Vector3D & other) const
operator+=()
Vector3D math::Vector3D::operator+= (const Vector3D & other)
operator-() [1/2]
Vector3D math::Vector3D::operator- () const
Renvoie le vecteur opposé (-x, -y, -z).
Returns
Un nouveau vecteur opposé.
operator-() [2/2]
Vector3D math::Vector3D::operator- (const Vector3D & other) const
operator-=()
Vector3D math::Vector3D::operator-= (const Vector3D & other)
operator/() [1/2]
Vector3D math::Vector3D::operator/ (const double scalar) const
operator/() [2/2]
Vector3D math::Vector3D::operator/ (const Vector3D & other) const
operator/=() [1/2]
Vector3D math::Vector3D::operator/= (const double scalar)
operator/=() [2/2]
Vector3D math::Vector3D::operator/= (const Vector3D & other)
Member Data Documentation
mX
double math::Vector3D::mX = 0
Composantes X, Y, Z du vecteur.
Definition at line 87 of file Math.hpp.
Referenced by raytracer::Cone::hits(), raytracer::Cylinder::hits(), raytracer::Rectangle3D::pointAt(), raytracer::Cone::rotateX(), raytracer::Cylinder::rotateX(), raytracer::Cone::rotateY(), raytracer::Cylinder::rotateY(), raytracer::Cone::rotateZ(), and raytracer::Cylinder::rotateZ().
mY
double math::Vector3D::mY = 0
Definition at line 88 of file Math.hpp.
Referenced by raytracer::Cone::hits(), raytracer::Cylinder::hits(), raytracer::Cone::rotateX(), raytracer::Cylinder::rotateX(), raytracer::Cone::rotateY(), raytracer::Cylinder::rotateY(), raytracer::Cone::rotateZ(), and raytracer::Cylinder::rotateZ().
mZ
double math::Vector3D::mZ = 0
Definition at line 89 of file Math.hpp.
Referenced by raytracer::Cone::getNormal(), raytracer::Cylinder::getNormal(), raytracer::Cone::hits(), raytracer::Cylinder::hits(), raytracer::Cone::rotateX(), raytracer::Cylinder::rotateX(), raytracer::Cone::rotateY(), raytracer::Cylinder::rotateY(), raytracer::Cone::rotateZ(), and raytracer::Cylinder::rotateZ().
The documentation for this class was generated from the following file:
src/core/math/Math.hpp