MyProject: raytracer::Parser Class Reference
raytracer::Parser Class Reference
#include <parse.hpp>
Public Member Functions
Parser (const std::string &filename, ErrorHandler &errorHandler)
bool parse (Scene &scene)
std::vector< Plane > parsePlanes ()
std::vector< Sphere > parseSpheres ()
Private Member Functions
bool parseCamera (Scene &scene)
bool parseLights (Scene &scene)
Private Attributes
libconfig::Config cfg_
ErrorHandler & errors_
Detailed Description
Definition at line 18 of file parse.hpp.
Constructor & Destructor Documentation
Parser()
raytracer::Parser::Parser (const std::string & filename, ErrorHandler & errorHandler)
Definition at line 27 of file parse.cpp.
    : errors_(errorHandler)
{
    try {
        cfg_.readFile(filename.c_str());
    } catch (const libconfig::FileIOException& fioex) {
        errors_.report("I/O error while reading file: " + filename);
    } catch (const libconfig::ParseException& pex) {
        errors_.report("Parse error at " + std::string(pex.getFile()) + ":" +
                       std::to_string(pex.getLine()) + " - " + pex.getError());
    }
}
References cfg_, errors_, and raytracer::ErrorHandler::report().
Member Function Documentation
parse()
bool raytracer::Parser::parse (Scene & scene)
Definition at line 40 of file parse.cpp.
{
    try {
        if (!parseCamera(scene)) return false;
        if (!parseLights(scene)) return false;
        auto planes = parsePlanes();
        auto spheres = parseSpheres();
        for (const auto& plane : planes) scene.addPlane(plane);
        for (const auto& sphere : spheres) scene.addSphere(sphere);
        return true;
    } catch (const libconfig::SettingException& ex) {
        errors_.report("Setting error: " + std::string(ex.what()));
        return false;
    }
}
References raytracer::Scene::addPlane(), raytracer::Scene::addSphere(), errors_, parseCamera(), parseLights(), parsePlanes(), parseSpheres(), and raytracer::ErrorHandler::report().
parseCamera()
bool raytracer::Parser::parseCamera (Scene & scene) private
Definition at line 55 of file parse.cpp.
{
    try {
        const Setting& cam = cfg_.lookup("camera");
        int width = cam["resolution"]["width"];
        int height = cam["resolution"]["height"];
        float px = cam["position"]["x"];
        float py = cam["position"]["y"];
        float pz = cam["position"]["z"];
        float lx = cam["look_at"]["x"];
        float ly = cam["look_at"]["y"];
        float lz = cam["look_at"]["z"];
        float fov;
        cam.lookupValue("fieldOfView", fov);
        Camera c;
        c.width = width;
        c.height = height;
        c._position = Point3D{px, py, pz};
        c.fieldOfView = fov;
        scene.setCamera(c);
    } catch (const libconfig::SettingException& e) {
        errors_.report("Camera parsing error: " + std::string(e.what()));
        return false;
    }
    return true;
}
References cfg_, errors_, raytracer::Camera::fieldOfView, raytracer::Camera::height, raytracer::ErrorHandler::report(), raytracer::Scene::setCamera(), and raytracer::Camera::width.
Referenced by parse().
parseLights()
bool raytracer::Parser::parseLights (Scene & scene) private
Definition at line 82 of file parse.cpp.
{
    try {
        const Setting& lights = cfg_.lookup("lights");
        if (lights.exists("ambient")) {
            double amb;
            lights.lookupValue("ambient", amb);
            scene.addAmbientLight(AmbientLight{amb, Color{1, 1, 1}});
        }
        if (lights.exists("point")) {
            const Setting& list = lights["point"];
            if (list.isList()) {
                for (int i = 0; i < list.getLength(); ++i) {
                    const Setting& it = list[i];
                    double diff;
                    if (!it.lookupValue("diffuse", diff)) {
                        errors_.report("Missing diffuse in point light");
                        return false;
                    }
                    const Setting& origin = it["origin"];
                    const Setting& color = it["color"];
                    double ox;
                    double oy;
                    double oz;
                    int cr;
                    int cg;
                    int cb;
                    origin.lookupValue("x", ox);
                    origin.lookupValue("y", oy);
                    origin.lookupValue("z", oz);
                    color.lookupValue("r", cr);
                    color.lookupValue("g", cg);
                    color.lookupValue("b", cb);
                    Color col{
                        static_cast<double>(cr),
                        static_cast<double>(cg),
                        static_cast<double>(cb)
                    };
                    std::map<std::string, Matrix4> allMatrix;
                    Vector3D rotation{0, 0, 0};
                    parseRotation(list, allMatrix, rotation);
                    scene.addPointLight(PointLight{diff, Point3D{ox, oy, oz}, col, rotation, allMatrix});
                }
            } else {
                errors_.report("'point' must be a list");
                return false;
            }
        }
        if (lights.exists("directional")) {
            const Setting& list = lights["directional"];
            if (list.isList()) {
                for (int i = 0; i < list.getLength(); ++i) {
                    const Setting& it = list[i];
                    double diff;
                    if (!it.lookupValue("diffuse", diff)) {
                        errors_.report("Missing diffuse in directional light");
                        return false;
                    }
                    const Setting& origin = it["origin"];
                    const Setting& direction = it["direction"];
                    const Setting& color = it["color"];
                    double ox;
                    double oy;
                    double oz;
                    double dx;
                    double dy;
                    double dz;
                    int cr;
                    int cg;
                    int cb;
                    origin.lookupValue("x", ox);
                    origin.lookupValue("y", oy);
                    origin.lookupValue("z", oz);
                    direction.lookupValue("x", dx);
                    direction.lookupValue("y", dy);
                    direction.lookupValue("z", dz);
                    color.lookupValue("r", cr);
                    color.lookupValue("g", cg);
                    color.lookupValue("b", cb);
                    Color col{
                        static_cast<double>(cr),
                        static_cast<double>(cg),
                        static_cast<double>(cb)
                    };
                    std::map<std::string, Matrix4> allMatrix;
                    Vector3D rotation{0, 0, 0};
                    scene.addDirectionalLight(DirectionalLight{
                        diff,
                        Point3D{ox, oy, oz},
                        Vector3D{dx, dy, dz},
                        col
                    });
                }
            } else {
                errors_.report("'directional' must be a list");
                return false;
            }
        }
    } catch (const libconfig::SettingException& e) {
        errors_.report("Lights parsing error: " + std::string(e.what()));
        return false;
    }
    return true;
}
References raytracer::Scene::addAmbientLight(), raytracer::Scene::addDirectionalLight(), raytracer::Scene::addPointLight(), cfg_, errors_, raytracer::parseRotation(), and raytracer::ErrorHandler::report().
Referenced by parse().
parsePlanes()
std::vector< Plane > raytracer::Parser::parsePlanes ()
Definition at line 371 of file parse.cpp.
{
    std::vector<Plane> planes;
    if (!cfg_.exists("primitives") || !cfg_.getRoot()["primitives"].exists("planes")) {
        return planes;
    }
    const libconfig::Setting& planes_setting = cfg_.getRoot()["primitives"]["planes"];
    planes = PrimitiveFact::createPlane(planes_setting, errors_);
    return planes;
}
References raytracer::PrimitiveFact::createPlane().
Referenced by parse().
parseSpheres()
std::vector< Sphere > raytracer::Parser::parseSpheres ()
Definition at line 384 of file parse.cpp.
{
    std::vector<Sphere> spheres;
    if (!cfg_.exists("primitives") || !cfg_.getRoot()["primitives"].exists("spheres")) {
        return spheres;
    }
    const libconfig::Setting& spheres_setting = cfg_.getRoot()["primitives"]["spheres"];
    spheres = PrimitiveFact::createSphere(spheres_setting, errors_);
    return spheres;
}
References raytracer::PrimitiveFact::createSphere().
Referenced by parse().
Member Data Documentation
cfg_
libconfig::Config raytracer::Parser::cfg_ private
Definition at line 27 of file parse.hpp.
Referenced by parseCamera(), parseLights(), and Parser().
errors_
ErrorHandler& raytracer::Parser::errors_ private
Definition at line 28 of file parse.hpp.
Referenced by parse(), parseCamera(), parseLights(), and Parser().
The documentation for this class was generated from the following files:
paser/parse.hpp
paser/parse.cpp