MyProject: core::Parser Class Reference
core::Parser Class Reference
Classe responsable du parsing des fichiers de configuration pour la scène 3D.
#include <Parser.hpp>
Public Member Functions
Parser (Camera &camera)
Constructeur du Parser.
~Parser ()=default
Destructeur par défaut.
void parseCamera (const libconfig::Config &cfg)
Parse la configuration de la caméra à partir d'un objet libconfig::Config.
void parsePrimitive (const libconfig::Config &cfg)
Parse les primitives de la scène à partir de la configuration.
void parseSpheres (const libconfig::Setting &spheresSetting)
Parse les sphères depuis un Setting libconfig.
void parsePlanes (const libconfig::Setting &planesSetting)
Parse les plans depuis un Setting libconfig.
void parseCylinders (const libconfig::Setting &cylindersSetting)
Parse les cylindres depuis un Setting libconfig.
void parseCones (const libconfig::Setting &conesSetting)
Parse les cônes depuis un Setting libconfig.
void parseLights (const libconfig::Config &cfg)
Parse les lumières depuis la configuration.
void parseFile (const string &filename)
Parse un fichier de configuration complet.
bool hasBasicElementInFiles ()
Vérifie si le fichier de configuration contient les éléments de base nécessaires.
vector< Sphere > getSpheres () const
Getter pour les sphères parsées.
vector< Cone > getCones () const
Getter pour les cônes parsés.
vector< Plane > getPlanes () const
Getter pour les plans parsés.
vector< Cylinder > getCylinders () const
Getter pour les cylindres parsés.
vector< PointLight > getPointLights () const
Getter pour les lumières ponctuelles parsées.
vector< DirectionalLight > getDirectionalLights () const
Getter pour les lumières directionnelles parsées.
double getAmbient () const
Getter pour la valeur d'éclairage ambiant.
double getDiffuse () const
Getter pour la valeur d'éclairage diffus.
Private Member Functions
void parseRotation (const libconfig::Setting &fileconfigRotation, std::map< string, math::Matrix< double > > &allMatrix, math::Vector3D &vectorRotation)
Parse la rotation depuis un Setting libconfig.
void parseTranslation (const libconfig::Setting &fileconfigTranslation, std::map< string, math::Matrix< double > > &allMatrix)
Parse la translation depuis un Setting libconfig.
void parseScale (const libconfig::Setting &fileconfigScale, std::map< string, math::Matrix< double > > &allMatrix)
Parse l'échelle (scale) depuis un Setting libconfig.
Private Attributes
Camera & _camera
Référence à la caméra à configurer.
double _ambient
Valeur de la lumière ambiante.
double _diffuse
Valeur de la lumière diffuse.
vector< Cylinder > _cylinders
Liste des cylindres parsés.
vector< DirectionalLight > _directionalLights
Liste des lumières directionnelles parsées.
vector< Plane > _planes
Liste des plans parsés.
vector< PointLight > _pointLights
Liste des lumières ponctuelles parsées.
vector< Sphere > _spheres
Liste des sphères parsées.
vector< Cone > _cones
Liste des cônes parsés.
Detailed Description
Classe responsable du parsing des fichiers de configuration pour la scène 3D.
La classe Parser analyse les fichiers de configuration (libconfig) pour extraire les paramètres de la caméra, les primitives (sphères, plans, cylindres, cônes), ainsi que les lumières directionnelles et ponctuelles. Elle stocke ensuite ces objets dans des collections internes accessibles via des getters.
Definition at line 44 of file Parser.hpp.
Constructor & Destructor Documentation
Parser()
core::Parser::Parser (Camera & camera) inline explicit
Constructeur du Parser.
Parameters
camera Référence à un objet Camera qui sera configuré via le parsing.
Definition at line 51 of file Parser.hpp.
: _camera(camera) {};
~Parser()
core::Parser::~Parser () default
Destructeur par défaut.
Member Function Documentation
getAmbient()
double core::Parser::getAmbient () const inline
Getter pour la valeur d'éclairage ambiant.
Returns
Valeur du paramètre ambient.
Definition at line 152 of file Parser.hpp.
{ return _ambient; };
References _ambient.
getCones()
vector< Cone > core::Parser::getCones () const inline
Getter pour les cônes parsés.
Returns
Un vecteur de Cone.
Definition at line 122 of file Parser.hpp.
{ return _cones; };
References _cones.
getCylinders()
vector< Cylinder > core::Parser::getCylinders () const inline
Getter pour les cylindres parsés.
Returns
Un vecteur de Cylinder.
Definition at line 134 of file Parser.hpp.
{ return _cylinders; };
References _cylinders.
getDiffuse()
double core::Parser::getDiffuse () const inline
Getter pour la valeur d'éclairage diffus.
Returns
Valeur du paramètre diffuse.
Definition at line 158 of file Parser.hpp.
{ return _diffuse; };
References _diffuse.
getDirectionalLights()
vector< DirectionalLight > core::Parser::getDirectionalLights () const inline
Getter pour les lumières directionnelles parsées.
Returns
Un vecteur de DirectionalLight.
Definition at line 146 of file Parser.hpp.
{ return _directionalLights; };
References _directionalLights.
getPlanes()
vector< Plane > core::Parser::getPlanes () const inline
Getter pour les plans parsés.
Returns
Un vecteur de Plane.
Definition at line 128 of file Parser.hpp.
{ return _planes; };
References _planes.
getPointLights()
vector< PointLight > core::Parser::getPointLights () const inline
Getter pour les lumières ponctuelles parsées.
Returns
Un vecteur de PointLight.
Definition at line 140 of file Parser.hpp.
{ return _pointLights; };
References _pointLights.
getSpheres()
vector< Sphere > core::Parser::getSpheres () const inline
Getter pour les sphères parsées.
Returns
Un vecteur de Sphere.
Definition at line 116 of file Parser.hpp.
{ return _spheres; };
References _spheres.
hasBasicElementInFiles()
bool core::Parser::hasBasicElementInFiles ()
Vérifie si le fichier de configuration contient les éléments de base nécessaires.
Returns
true si les éléments de base sont présents, false sinon.
Referenced by core::RayTracer::run().
parseCamera()
void core::Parser::parseCamera (const libconfig::Config & cfg)
Parse la configuration de la caméra à partir d'un objet libconfig::Config.
Parse la configuration de la caméra à partir du fichier de configuration.
Parameters
cfg Référence constante vers la configuration libconfig.
Cette méthode extrait la résolution, la position, le champ de vision, ainsi que les matrices de transformation (rotation et translation) pour la caméra.
Parameters
cfg Référence constante vers l'objet libconfig::Config contenant la configuration.
< Largeur de la caméra
< Hauteur de la caméra
< Position X de la caméra
< Position Y de la caméra
< Position Z de la caméra
< Champ de vision
< Matrices de transformation
< Rotation sous forme de vecteur
Definition at line 33 of file Parser.cpp.
 {
     if (cfg.exists("camera")) {
         try {
             const libconfig::Setting &cameraSetting = cfg.lookup("camera");
             const libconfig::Setting &resolution = cameraSetting["resolution"];
             const libconfig::Setting &position = cameraSetting["position"];
             map<string, math::Matrix<double>> allMatrix;
             math::Vector3D vectorRotation;
             _camera.width = resolution["width"];
             _camera.height = resolution["height"];
             _camera.posX = position["x"];
             _camera.posY = position["y"];
             _camera.posZ = position["z"];
             _camera.fieldOfView = cameraSetting["fieldOfView"];
             parseRotation(cameraSetting, allMatrix, vectorRotation);
             parseTranslation(cameraSetting, allMatrix);
             _camera.mAllMatrix = allMatrix;
             _camera.mVectorRotation = vectorRotation;
         } catch (const libconfig::SettingNotFoundException &) {
             cerr << "One or many configuration are missing or incorrect with Camera\n";
         }
     }
 }
References _camera, raytracer::Camera::fieldOfView, raytracer::Camera::height, raytracer::Camera::mAllMatrix, raytracer::Camera::mVectorRotation, parseRotation(), parseTranslation(), raytracer::Camera::posX, raytracer::Camera::posY, raytracer::Camera::posZ, and raytracer::Camera::width.
parseCones()
void core::Parser::parseCones (const libconfig::Setting & conesSetting)
Parse les cônes depuis un Setting libconfig.
Parameters
conesSetting Référence constante vers la liste des cônes dans la config.
parseCylinders()
void core::Parser::parseCylinders (const libconfig::Setting & cylindersSetting)
Parse les cylindres depuis un Setting libconfig.
Parameters
cylindersSetting Référence constante vers la liste des cylindres dans la config.
parseFile()
void core::Parser::parseFile (const string & filename)
Parse un fichier de configuration complet.
Parameters
filename Nom du fichier de configuration.
Referenced by core::RayTracer::run().
parseLights()
void core::Parser::parseLights (const libconfig::Config & cfg)
Parse les lumières depuis la configuration.
Parameters
cfg Référence constante vers la configuration libconfig.
parsePlanes()
void core::Parser::parsePlanes (const libconfig::Setting & planesSetting)
Parse les plans depuis un Setting libconfig.
Parse les plans configurés dans la scène.
Parameters
planesSetting Référence constante vers la liste des plans dans la config.
Pour chaque plan, récupère l'axe, la position, la rotation, la translation, la couleur, et applique les matrices de transformation correspondantes.
Parameters
planesSetting Référence constante vers le Setting contenant la liste des plans.
Definition at line 101 of file Parser.cpp.
 {
     const int planesLength = planesSetting.getLength();
     for (int i = 0; i < planesLength; i++) {
         map<string, math::Matrix<double>> allMatrix;
         math::Vector3D vectorRotation(0, 0, 0);
         string axis = static_cast<string>(planesSetting[i]["axis"]);
         int position = planesSetting[i]["position"];
         try {
             const double rotation = planesSetting[i]["rotation"];
             const double translation = planesSetting[i]["translation"];
             // Définit les matrices de rotation et translation selon l'axe
             // ... (le code ici) ...
         } catch (const libconfig::SettingNotFoundException &) {
             // Gestion de l'absence des données de rotation ou translation
         }
         const libconfig::Setting &color = planesSetting[i]["color"];
         raytracer::Color colors(color["r"], color["g"], color["b"]);
         _planes.emplace_back(axis, position, colors, allMatrix, vectorRotation);
     }
 }
References _planes.
parsePrimitive()
void core::Parser::parsePrimitive (const libconfig::Config & cfg)
Parse les primitives de la scène à partir de la configuration.
Parameters
cfg Référence constante vers la configuration libconfig.
parseRotation()
void core::Parser::parseRotation (const libconfig::Setting & fileconfigRotation, std::map< string, math::Matrix< double > > & allMatrix, math::Vector3D & vectorRotation) private
Parse la rotation depuis un Setting libconfig.
Parse la rotation à partir d'un Setting libconfig.
Parameters
fileconfigRotation Référence vers le Setting rotation.
allMatrix Map pour stocker les matrices de transformation.
vectorRotation Vector3D pour stocker les angles de rotation.
Cette méthode lit les valeurs de rotation sur les axes X, Y et Z en degrés, les convertit en radians, puis construit les matrices de rotation correspondantes.
Parameters
fileconfigRotation Référence constante vers le Setting contenant la rotation.
allMatrix Référence vers une map pour stocker les matrices de rotation.
vectorRotation Référence vers un Vector3D pour stocker les angles de rotation.
Definition at line 139 of file Parser.cpp.
 {
     double rotationX = 0.0;
     double rotationY = 0.0;
     double rotationZ = 0.0;
     try {
         const libconfig::Setting &rotation = fileconfigRotation["rotation"];
         // Récupération de la valeur X
         if (!rotation.lookupValue("x", rotationX)) {
             int tmp;
             if (rotation.lookupValue("x", tmp))
                 rotationX = static_cast<double>(tmp);
             else exit(84);
         }
         // Récupération de la valeur Y
         if (!rotation.lookupValue("y", rotationY)) {
             int tmp;
             if (rotation.lookupValue("y", tmp))
                 rotationY = static_cast<double>(tmp);
             else exit(84);
         }
         // Récupération de la valeur Z
         if (!rotation.lookupValue("z", rotationZ)) {
             int tmp;
             if (rotation.lookupValue("z", tmp))
                 rotationZ = static_cast<double>(tmp);
             else exit(84);
         }
         // Conversion degrés -> radians
         rotationX = (rotationX * M_PI) / 180.0;
         rotationY = (rotationY * M_PI) / 180.0;
         rotationZ = (rotationZ * M_PI) / 180.0;
         // Construction des matrices de rotation
         allMatrix["rotationX"] = {
             {1.0, 0.0, 0.0, 0.0},
             {0.0, std::cos(rotationX), -std::sin(rotationX), 0.0},
             {0.0, std::sin(rotationX),  std::cos(rotationX), 0.0},
             {0.0, 0.0, 0.0, 1.0}
         };
         allMatrix["rotationY"] = {
             {std::cos(rotationY), 0.0, std::sin(rotationY), 0.0},
             {0.0, 1.0, 0.0, 0.0},
             {-std::sin(rotationY), 0.0, std::cos(rotationY), 0.0},
             {0.0, 0.0, 0.0, 1.0}
         };
         allMatrix["rotationZ"] = {
             {std::cos(rotationZ), -std::sin(rotationZ), 0.0, 0.0},
             {std::sin(rotationZ),  std::cos(rotationZ), 0.0, 0.0},
             {0.0, 0.0, 1.0, 0.0},
             {0.0, 0.0, 0.0, 1.0}
         };
     }
     catch (const libconfig::SettingNotFoundException &) {
         // Si aucune rotation définie, aucune action
     }
     vectorRotation = math::Vector3D(rotationX, rotationY, rotationZ);
 }
Referenced by parseCamera(), and parseSpheres().
parseScale()
void core::Parser::parseScale (const libconfig::Setting & fileconfigScale, std::map< string, math::Matrix< double > > & allMatrix) private
Parse l'échelle (scale) depuis un Setting libconfig.
Parameters
fileconfigScale Référence vers le Setting scale.
allMatrix Map pour stocker les matrices de transformation.
Referenced by parseSpheres().
parseSpheres()
void core::Parser::parseSpheres (const libconfig::Setting & spheresSetting)
Parse les sphères depuis un Setting libconfig.
Parse les sphères configurées dans la scène.
Parameters
spheresSetting Référence constante vers la liste des sphères dans la config.
Pour chaque sphère, cette méthode récupère les coordonnées, le rayon, la couleur et applique les transformations de rotation, translation et échelle.
Parameters
spheresSetting Référence constante vers le Setting contenant la liste des sphères.
Definition at line 69 of file Parser.cpp.
 {
     const int spheresLength = spheresSetting.getLength();
     for (int i = 0; i < spheresLength; i++) {
         map<string, math::Matrix<double>> allMatrix;
         math::Vector3D vectorRotation;
         int x = spheresSetting[i]["x"];
         int y = spheresSetting[i]["y"];
         int z = spheresSetting[i]["z"];
         int r = spheresSetting[i]["r"];
         const libconfig::Setting &color = spheresSetting[i]["color"];
         raytracer::Color colors(color["r"], color["g"], color["b"]);
         parseTranslation(spheresSetting[i], allMatrix);
         parseRotation(spheresSetting[i], allMatrix, vectorRotation);
         parseScale(spheresSetting[i], allMatrix);
         _spheres.emplace_back(x, y, z, r, colors, allMatrix, vectorRotation);
     }
 }
References _spheres, parseRotation(), parseScale(), and parseTranslation().
parseTranslation()
void core::Parser::parseTranslation (const libconfig::Setting & fileconfigTranslation, std::map< string, math::Matrix< double > > & allMatrix) private
Parse la translation depuis un Setting libconfig.
Parameters
fileconfigTranslation Référence vers le Setting translation.
allMatrix Map pour stocker les matrices de transformation.
Referenced by parseCamera(), and parseSpheres().
Member Data Documentation
_ambient
double core::Parser::_ambient private
Valeur de la lumière ambiante.
Definition at line 194 of file Parser.hpp.
Referenced by getAmbient().
_camera
Camera& core::Parser::_camera private
Référence à la caméra à configurer.
Definition at line 193 of file Parser.hpp.
Referenced by parseCamera().
_cones
vector<Cone> core::Parser::_cones private
Liste des cônes parsés.
Definition at line 202 of file Parser.hpp.
Referenced by getCones().
_cylinders
vector<Cylinder> core::Parser::_cylinders private
Liste des cylindres parsés.
Definition at line 197 of file Parser.hpp.
Referenced by getCylinders().
_diffuse
double core::Parser::_diffuse private
Valeur de la lumière diffuse.
Definition at line 195 of file Parser.hpp.
Referenced by getDiffuse().
_directionalLights
vector<DirectionalLight> core::Parser::_directionalLights private
Liste des lumières directionnelles parsées.
Definition at line 198 of file Parser.hpp.
Referenced by getDirectionalLights().
_planes
vector<Plane> core::Parser::_planes private
Liste des plans parsés.
Definition at line 199 of file Parser.hpp.
Referenced by getPlanes(), and parsePlanes().
_pointLights
vector<PointLight> core::Parser::_pointLights private
Liste des lumières ponctuelles parsées.
Definition at line 200 of file Parser.hpp.
Referenced by getPointLights().
_spheres
vector<Sphere> core::Parser::_spheres private
Liste des sphères parsées.
Definition at line 201 of file Parser.hpp.
Referenced by getSpheres(), and parseSpheres().
The documentation for this class was generated from the following files:
src/parser/Parser.hpp
src/parser/Parser.cpp