MyProject: raytracer::PrimitiveFact Class Reference
raytracer::PrimitiveFact Class Reference
#include <Primitive_fact.hpp>
Static Public Member Functions
static std::vector< Plane > createPlane (const libconfig::Setting &setting, ErrorHandler &errors)
static std::vector< Sphere > createSphere (const libconfig::Setting &setting, ErrorHandler &errors)
Detailed Description
Definition at line 21 of file Primitive_fact.hpp.
Member Function Documentation
createPlane()
std::vector< Plane > raytracer::PrimitiveFact::createPlane (const libconfig::Setting & setting, ErrorHandler & errors) static
Definition at line 19 of file Primitive_fact.cpp.
{
        std::vector<Plane> planes;
        if (setting.isList()) {
            for (int i = 0; i < setting.getLength(); ++i) {
                auto plane = parseSinglePlane(setting[i], errors);
                if (plane) {
                    planes.push_back(*plane);
                }
            }
        } else {
            auto plane = parseSinglePlane(setting, errors);
            if (plane) {
                planes.push_back(*plane);
            }
        }
        return planes;
    }
References raytracer::parseSinglePlane().
Referenced by raytracer::Parser::parsePlanes().
createSphere()
std::vector< Sphere > raytracer::PrimitiveFact::createSphere (const libconfig::Setting & setting, ErrorHandler & errors) static
Definition at line 134 of file Primitive_fact.cpp.
{
        std::vector<Sphere> spheres;
        if (setting.isList()) {
            for (int i = 0; i < setting.getLength(); ++i) {
                auto sphere = parseSingleSphere(setting[i], errors);
                if (sphere) {
                    spheres.push_back(*sphere);
                }
            }
        } else {
            auto sphere = parseSingleSphere(setting, errors);
            if (sphere) {
                spheres.push_back(*sphere);
            }
        }
        return spheres;
    }
References raytracer::parseSingleSphere().
Referenced by raytracer::Parser::parseSpheres().
The documentation for this class was generated from the following files:
paser/Primitive_fact.hpp
paser/Primitive_fact.cpp