MyProject: raytracer::PointLight Class Reference
raytracer::PointLight Class Reference
Classe représentant une source lumineuse ponctuelle (point light).
#include <PointLight.hpp>
Public Member Functions
PointLight ()=default
Constructeur par défaut.
PointLight (const int originX, const int originY, const int originZ, const Color &color, const map< string, math::Matrix< double > > &allMatrix, const math::Vector3D vectorRotation)
Constructeur avec paramètres pour initialiser la source lumineuse.
~PointLight () override=default
Destructeur virtuel par défaut.
Color getColorShadow (const math::Point3D &intersectionPoint, const math::Vector3D &normal, const vector< unique_ptr< IPrimitive > > &primitives) override
Calcule la couleur de l'ombre au point d'intersection donné.
Public Member Functions inherited from raytracer::ILight
virtual ~ILight ()=default
Destructeur virtuel par défaut.
virtual Color getColorShadow (const math::Point3D &intersectionPoint, const math::Vector3D &normal, const vector< unique_ptr< IPrimitive > > &primitives)=0
Calcule la couleur de la lumière en tenant compte des ombres.
Public Attributes
math::Point3D mOrigin
Position de la source lumineuse dans l'espace.
Color mColor
Couleur de la source lumineuse.
map< string, math::Matrix< double > > mAllMatrix
Matrices associées à la lumière (transformations, rotations).
math::Vector3D mVectorRotation
Vecteur représentant la rotation appliquée.
Public Attributes inherited from raytracer::ILight
math::Point3D mBaseOrigin
math::Vector3D mBaseDirection
Color mBaseColor
math::Vector3D mBaseVectorRotation
Detailed Description
Classe représentant une source lumineuse ponctuelle (point light).
Cette classe dérive de l'interface ILight et modélise une lumière émise à partir d'un point dans l'espace, avec gestion de la couleur, position et rotation.
Definition at line 24 of file PointLight.hpp.
Constructor & Destructor Documentation
PointLight() [1/2]
raytracer::PointLight::PointLight () default
Constructeur par défaut.
PointLight() [2/2]
raytracer::PointLight::PointLight (const int originX, const int originY, const int originZ, const Color & color, const map< string, math::Matrix< double > > & allMatrix, const math::Vector3D vectorRotation) inline
Constructeur avec paramètres pour initialiser la source lumineuse.
Parameters
originX Coordonnée X de l'origine de la lumière.
originY Coordonnée Y de l'origine de la lumière.
originZ Coordonnée Z de l'origine de la lumière.
color Couleur de la lumière.
allMatrix Ensemble de matrices (potentiellement de transformation).
vectorRotation Vecteur représentant la rotation de la lumière.
Definition at line 41 of file PointLight.hpp.
            : mOrigin(originX, originY, originZ), mColor(color),
              mAllMatrix(allMatrix), mVectorRotation(vectorRotation) {}
~PointLight()
raytracer::PointLight::~PointLight () override default
Destructeur virtuel par défaut.
Member Function Documentation
getColorShadow()
Color raytracer::PointLight::getColorShadow (const math::Point3D & intersectionPoint, const math::Vector3D & normal, const vector< unique_ptr< IPrimitive > > & primitives) override virtual
Calcule la couleur de l'ombre au point d'intersection donné.
Calcule la couleur d'ombre (shadow) en un point d'intersection donné.
Cette méthode vérifie si la lumière est bloquée par une primitive entre le point d'intersection et la source lumineuse. Si bloquée, retourne noir.
Parameters
intersectionPoint Point d'intersection dans la scène.
normal Normale à la surface au point d'intersection.
primitives Liste des primitives dans la scène.
Returns
Color Couleur de l'ombre ou lumière.
Cette méthode détermine si le point d'intersection est dans l'ombre par rapport à cette source lumineuse ponctuelle, en lançant un rayon d'ombre vers la source. Si un objet bloque la lumière, la couleur retournée est noire. Sinon, la couleur de la lumière est calculée en fonction de la distance.
Parameters
intersectionPoint Le point d'intersection dans la scène.
normal La normale à la surface au point d'intersection.
primitives La liste des primitives de la scène.
Returns
Color La couleur résultante en tenant compte de l'ombre.
Implements raytracer::ILight.
Definition at line 27 of file PointLight.cpp.
{
    World world;
    // Direction du rayon allant du point d'intersection vers la source lumineuse
    const math::Vector3D lightDir = (mBaseOrigin - intersectionPoint);
    // Création d'un rayon d'ombre légèrement décalé pour éviter les auto-intersections
    const Ray shadowRay(
        intersectionPoint + (normal * 0.01),
        math::Vector3D::normalize(lightDir)
    );
    // Recherche de l'intersection la plus proche entre le rayon d'ombre et les primitives
    const double closestHit = world.hit(shadowRay, primitives);
    // Si une intersection est trouvée avant la lumière, le point est dans l'ombre
    if (closestHit < lightDir.length()) {
        return Color(0.0, 0.0, 0.0); // Couleur noire (ombre)
    }
    // Sinon, calcul de la couleur de la lumière en fonction de la distance
    return mBaseColor * world.getDistance(
        mBaseOrigin, intersectionPoint
    );
}
References raytracer::World::getDistance(), raytracer::World::hit(), math::Vector3D::length(), raytracer::ILight::mBaseColor, raytracer::ILight::mBaseOrigin, and math::Vector3D::normalize().
Member Data Documentation
mAllMatrix
map<string, math::Matrix<double> > raytracer::PointLight::mAllMatrix
Matrices associées à la lumière (transformations, rotations).
Definition at line 72 of file PointLight.hpp.
mColor
Color raytracer::PointLight::mColor
Couleur de la source lumineuse.
Definition at line 71 of file PointLight.hpp.
mOrigin
math::Point3D raytracer::PointLight::mOrigin
Position de la source lumineuse dans l'espace.
Definition at line 70 of file PointLight.hpp.
mVectorRotation
math::Vector3D raytracer::PointLight::mVectorRotation
Vecteur représentant la rotation appliquée.
Definition at line 73 of file PointLight.hpp.
The documentation for this class was generated from the following files:
src/lights/pointLight/PointLight.hpp
src/lights/pointLight/PointLight.cpp