MyProject: src/core/helpers/Color.cpp File Reference
Color.cpp File Reference
#include "Color.hpp"
Functions
ostream & operator<< (ostream &os, const raytracer::Color &c)
Function Documentation
operator<<()
ostream & operator<< (ostream & os, const raytracer::Color & c)
Definition at line 10 of file Color.cpp.
{
    os << static_cast<int>(c.getR() * 255) << " "
        << static_cast<int>(c.getG() * 255) << " "
        << static_cast<int>(c.getB() * 255) << "\n";
    return os;
}
References raytracer::Color::getB(), raytracer::Color::getG(), and raytracer::Color::getR().