MyProject: raytracer Namespace Reference
raytracer Namespace Reference
Classes
class ArgumentError
Exception levée lors d'une erreur dans les arguments d'une fonction.
class Camera
Classe représentant une caméra dans le moteur de raytracing.
class Color
class Cone
Classe représentant un cône dans un moteur de raytracing.
class Cylinder
Représente un cylindre utilisé dans le moteur de raytracing.
class DirectionalLight
class ErrorHandler
class Factory
Gère la création d'objets (primitives et lumières) dans le moteur de raytracing.
class ILight
Interface abstraite représentant une source lumineuse dans la scène.
class Image
Classe représentant une image 2D pouvant être affichée via SFML ou exportée en PPM.
class IPrimitive
Interface de base pour les primitives géométriques dans le moteur de raytracing.
class MatrixError
Exception levée lors d'une erreur de manipulation de matrice.
class ParseError
Exception levée lors d'une erreur de parsing (analyse de scène, etc.).
class Parser
class Plane
Représente un plan dans la scène de raytracing.
class PointLight
Classe représentant une source lumineuse ponctuelle (point light).
class PrimitiveFact
class Ray
class Rectangle3D
class Scene
Classe représentant une scène 3D pour le ray tracing.
class Sphere
Représente une sphère dans la scène 3D pour le moteur de raytracing.
class World
Functions
void parseRotation (const libconfig::Setting &fileconfigRotation, map< string, math::Matrix< double > > &allMatrix, math::Vector3D &vectorRotation)
void parseTranslation (const libconfig::Setting &fileconfigTranslation, map< string, math::Matrix< double > > &allMatrix)
void parseScale (const libconfig::Setting &fileconfigScale, map< string, math::Matrix< double > > &allMatrix)
void calcFinalTransformationMatrix (map< string, math::Matrix< double > > &allMatrix)
static std::unique_ptr< Plane > parseSinglePlane (const libconfig::Setting &setting, ErrorHandler &errors)
static std::unique_ptr< Sphere > parseSingleSphere (const libconfig::Setting &setting, ErrorHandler &errors)
Function Documentation
calcFinalTransformationMatrix()
void raytracer::calcFinalTransformationMatrix (map< string, math::Matrix< double > > & allMatrix)
Definition at line 344 of file parse.cpp.
{
    allMatrix["final"] = {
        {1.0, 0.0, 0.0, 0.0},
        {0.0, 1.0, 0.0, 0.0},
        {0.0, 0.0, 1.0, 0.0},
        {0.0, 0.0, 0.0, 1.0}
    };
    if (allMatrix.find("translation") != allMatrix.end()) {
        allMatrix["final"] *= allMatrix["translation"];
    }
    if (allMatrix.find("scale") != allMatrix.end()) {
        allMatrix["final"] *= allMatrix["scale"];
    }
    if (allMatrix.find("rotation") != allMatrix.end()) {
        allMatrix["final"] *= allMatrix["rotation"];
    } else {
        if (allMatrix.find("rotationX") != allMatrix.end()) {
            allMatrix["final"] *= allMatrix["rotationX"];
            allMatrix["final"] *= allMatrix["rotationY"];
            allMatrix["final"] *= allMatrix["rotationZ"];
        }
    }
}
parseRotation()
void raytracer::parseRotation (const libconfig::Setting & fileconfigRotation, map< string, math::Matrix< double > > & allMatrix, math::Vector3D & vectorRotation)
Definition at line 189 of file parse.cpp.
{
    double rotationX = 0.0;
    double rotationY = 0.0;
    double rotationZ = 0.0;
    try {
        const libconfig::Setting &rotation = fileconfigRotation["rotation"];
        try {
            rotationX = rotation["x"];
        } catch (const libconfig::ConfigException &) {
            try {
                rotationX = static_cast<double>(static_cast<int>(rotation["x"]));
            } catch (const libconfig::ConfigException &) {
                cerr << "Not found rotation in axe X or value incorrect\n";
                ::exit(84);
            }
        }
        try {
            rotationY = rotation["y"];
        } catch (const libconfig::ConfigException &) {
            try {
                rotationY = static_cast<double>(static_cast<int>(rotation["y"]));
            } catch (const libconfig::ConfigException &) {
                cerr << "Not found rotation in axe Y or value incorrect\n";
                ::exit(84);
            }
        }
        try {
            rotationZ = rotation["z"];
        } catch (const libconfig::ConfigException &) {
            try {
                rotationZ = static_cast<double>(static_cast<int>(rotation["z"]));
            } catch (const libconfig::ConfigException &) {
                cerr << "Not found rotation in axe Z or value incorrect\n";
                ::exit(84);
            }
        }
        rotationX = (rotationX * M_PI) / 180.0;
        rotationY = (rotationY * M_PI) / 180.0;
        rotationZ = (rotationZ * M_PI) / 180.0;
        allMatrix["rotationX"] = {
            {1.0, 0.0, 0.0, 0.0},
            {0.0, ::cos(rotationX), -::sin(rotationX), 0.0},
            {0, ::sin(rotationX), ::cos(rotationX), 0.0},
            {0.0, 0.0, 0.0, 1.0}
        };
        allMatrix["rotationY"] = {
            {::cos(rotationY), 0.0, ::sin(rotationY), 0.0},
            {0.0, 1.0, 0.0, 0.0},
            {-::sin(rotationY), 0, ::cos(rotationY), 0.0},
            {0.0, 0.0, 0.0, 1.0}
        };
        allMatrix["rotationZ"] = {
            {::cos(rotationZ), -::sin(rotationZ), 0.0, 0.0},
            {::sin(rotationZ), ::cos(rotationZ), 0.0, 0.0},
            {0.0, 0.0, 1.0, 0.0},
            {0.0, 0.0, 0.0, 1.0}
        };
    } catch (const libconfig::SettingNotFoundException &) {
    }
    vectorRotation = math::Vector3D(rotationX, rotationY, rotationZ);
}
Referenced by raytracer::Parser::parseLights().
parseScale()
void raytracer::parseScale (const libconfig::Setting & fileconfigScale, map< string, math::Matrix< double > > & allMatrix)
Definition at line 302 of file parse.cpp.
{
    double scaleX = 1.0;
    double scaleY = 1.0;
    double scaleZ = 1.0;
    try {
        const libconfig::Setting &scale = fileconfigScale["scale"];
        try {
            scaleX = scale["x"];
        } catch (const libconfig::ConfigException &) {
            try {
                scaleX = static_cast<double>(static_cast<int>(scale["x"]));
            } catch (const libconfig::ConfigException &) {
            }
        }
        try {
            scaleY = scale["y"];
        } catch (const libconfig::ConfigException &) {
            try {
                scaleY = static_cast<double>(static_cast<int>(scale["y"]));
            } catch (const libconfig::ConfigException &) {
            }
        }
        try {
            scaleZ = scale["z"];
        } catch (const libconfig::ConfigException &) {
            try {
                scaleZ = static_cast<double>(static_cast<int>(scale["z"]));
            } catch (const libconfig::ConfigException &) {
            }
        }
        allMatrix["scale"] = {
            {scaleX, 0.0, 0.0, 0.0},
            {0.0, scaleY, 0.0, 0.0},
            {0.0, 0.0, scaleZ, 0.0},
            {0.0, 0.0, 0.0, 1.0}
        };
    } catch (const libconfig::SettingNotFoundException &) {
    }
}
parseSinglePlane()
static std::unique_ptr< Plane > raytracer::parseSinglePlane (const libconfig::Setting & setting, ErrorHandler & errors) static
Definition at line 39 of file Primitive_fact.cpp.
{
        std::string axis;
        int position;
        int cr, cg, cb;
        std::string rotationAxis;
        float rotationAngle = 0.0f;
        float translationX = 0.0f, translationY = 0.0f, translationZ = 0.0f;
        if (!setting.lookupValue("axis", axis) ||
            !setting.lookupValue("position", position)) {
            errors.report("Missing axis or position for plane");
            return nullptr;
        }
        if (!setting.exists("color") ||
            !setting["color"].lookupValue("r", cr) ||
            !setting["color"].lookupValue("g", cg) ||
            !setting["color"].lookupValue("b", cb)) {
            errors.report("Missing or invalid color for plane");
            return nullptr;
        }
        if (axis != "X" && axis != "Y" && axis != "Z") {
            errors.report("Invalid axis for plane: must be X, Y, or Z");
            return nullptr;
        }
        if (cr < 0 || cr > 255 || cg < 0 || cg > 255 || cb < 0 || cb > 255) {
            errors.report("Invalid color values for plane: must be between 0 and 255");
            return nullptr;
        }
        if (setting.lookupValue("rotationAxis", rotationAxis)) {
            if (rotationAxis != "X" && rotationAxis != "Y" && rotationAxis != "Z") {
                errors.report("Invalid rotation axis for plane: must be X, Y, or Z");
                return nullptr;
            }
            if (!setting.lookupValue("rotationAngle", rotationAngle)) {
                errors.report("Missing rotation angle for plane");
                return nullptr;
            }
        }
        setting.lookupValue("translationX", translationX);
        setting.lookupValue("translationY", translationY);
        setting.lookupValue("translationZ", translationZ);
        math::Vector3D rotationVector(0, 0, 0);
        if (rotationAxis == "X") {
            rotationVector.x = rotationAngle;
        } else if (rotationAxis == "Y") {
            rotationVector.y = rotationAngle;
        } else if (rotationAxis == "Z") {
            rotationVector.z = rotationAngle;
        }
        map<string, math::Matrix<double>> allMatrix;
        if (!rotationAxis.empty()) {
            math::Matrix<double> rotationMatrix(4, 4);
            if (rotationAxis == "X") {
                double rad = rotationAngle * M_PI / 180.0;
                rotationMatrix = math::Matrix<double>(4, 4, {
                    1, 0, 0, 0,
                    0, cos(rad), -sin(rad), 0,
                    0, sin(rad), cos(rad), 0,
                    0, 0, 0, 1
                });
            } else if (rotationAxis == "Y") {
                double rad = rotationAngle * M_PI / 180.0;
                rotationMatrix = math::Matrix<double>(4, 4, {
                    cos(rad), 0, sin(rad), 0,
                    0, 1, 0, 0,
                    -sin(rad), 0, cos(rad), 0,
                    0, 0, 0, 1
                });
            } else if (rotationAxis == "Z") {
                double rad = rotationAngle * M_PI / 180.0;
                rotationMatrix = math::Matrix<double>(4, 4, {
                    cos(rad), -sin(rad), 0, 0,
                    sin(rad), cos(rad), 0, 0,
                    0, 0, 1, 0,
                    0, 0, 0, 1
                });
            }
            allMatrix["rotation"] = rotationMatrix;
        }
        math::Matrix<double> translationMatrix(4, 4, {
            1, 0, 0, translationX,
            0, 1, 0, translationY,
            0, 0, 1, translationZ,
            0, 0, 0, 1
        });
        allMatrix["translation"] = translationMatrix;
        auto plane = std::make_unique<Plane>(axis, position, Color{cr, cg, cb}, rotationVector, allMatrix);
        return plane;
        //return std::make_unique<Plane>(axis, position, Color{cr, cg, cb});
    }
References raytracer::ErrorHandler::report().
Referenced by raytracer::PrimitiveFact::createPlane().
parseSingleSphere()
static std::unique_ptr< Sphere > raytracer::parseSingleSphere (const libconfig::Setting & setting, ErrorHandler & errors) static
Definition at line 154 of file Primitive_fact.cpp.
{
        double x, y, z, r;
        int cr, cg, cb;
        std::string rotationAxis;
        float rotationAngle = 0.0f;
        float translationX = 0.0f, translationY = 0.0f, translationZ = 0.0f;
        if (!setting.lookupValue("x", x) ||
            !setting.lookupValue("y", y) ||
            !setting.lookupValue("z", z) ||
            !setting.lookupValue("r", r)) {
            errors.report("Missing coordinates or radius for sphere");
            return nullptr;
        }
        if (!setting.exists("color") ||
            !setting["color"].lookupValue("r", cr) ||
            !setting["color"].lookupValue("g", cg) ||
            !setting["color"].lookupValue("b", cb)) {
            errors.report("Missing or invalid color for sphere");
            return nullptr;
        }
        if (r <= 0) {
            errors.report("Invalid radius for sphere: must be positive");
            return nullptr;
        }
        if (cr < 0 || cr > 255 || cg < 0 || cg > 255 || cb < 0 || cb > 255) {
            errors.report("Invalid color values for sphere: must be between 0 and 255");
            return nullptr;
        }
        if (setting.lookupValue("rotationAxis", rotationAxis)) {
            if (rotationAxis != "X" && rotationAxis != "Y" && rotationAxis != "Z") {
                errors.report("Invalid rotation axis for sphere: must be X, Y, or Z");
                return nullptr;
            }
            if (!setting.lookupValue("rotationAngle", rotationAngle)) {
                errors.report("Missing rotation angle for sphere");
                return nullptr;
            }
        }
        setting.lookupValue("translationX", translationX);
        setting.lookupValue("translationY", translationY);
        setting.lookupValue("translationZ", translationZ);
        math::Vector3D rotationVector(0, 0, 0);
        if (rotationAxis == "X") {
            rotationVector.x = rotationAngle;
        } else if (rotationAxis == "Y") {
            rotationVector.y = rotationAngle;
        } else if (rotationAxis == "Z") {
            rotationVector.z = rotationAngle;
        }
        map<string, math::Matrix<double>> allMatrix;
        if (!rotationAxis.empty()) {
            math::Matrix<double> rotationMatrix(4, 4);
            if (rotationAxis == "X") {
                double rad = rotationAngle * M_PI / 180.0;
                rotationMatrix = math::Matrix<double>(4, 4, {
                    1, 0, 0, 0,
                    0, cos(rad), -sin(rad), 0,
                    0, sin(rad), cos(rad), 0,
                    0, 0, 0, 1
                });
            } else if (rotationAxis == "Y") {
                double rad = rotationAngle * M_PI / 180.0;
                rotationMatrix = math::Matrix<double>(4, 4, {
                    cos(rad), 0, sin(rad), 0,
                    0, 1, 0, 0,
                    -sin(rad), 0, cos(rad), 0,
                    0, 0, 0, 1
                });
            } else if (rotationAxis == "Z") {
                double rad = rotationAngle * M_PI / 180.0;
                rotationMatrix = math::Matrix<double>(4, 4, {
                    cos(rad), -sin(rad), 0, 0,
                    sin(rad), cos(rad), 0, 0,
                    0, 0, 1, 0,
                    0, 0, 0, 1
                });
            }
            allMatrix["rotation"] = rotationMatrix;
        }
        math::Matrix<double> translationMatrix(4, 4, {
            1, 0, 0, translationX,
            0, 1, 0, translationY,
            0, 0, 1, translationZ,
            0, 0, 0, 1
        });
        allMatrix["translation"] = translationMatrix;
        auto sphere = std::make_unique<Sphere>(math::Point3D{x, y, z}, static_cast<float>(r), Color{cr, cg, cb}, rotationVector, allMatrix);
        return sphere;
        //return std::make_unique<Sphere>(math::Point3D{x, y, z}, static_cast<float>(r), Color{cr, cg, cb});
    }
References raytracer::ErrorHandler::report().
Referenced by raytracer::PrimitiveFact::createSphere().
parseTranslation()
void raytracer::parseTranslation (const libconfig::Setting & fileconfigTranslation, map< string, math::Matrix< double > > & allMatrix)
Definition at line 254 of file parse.cpp.
{
    double translationX = 0;
    double translationY = 0;
    double translationZ = 0;
    try {
        const libconfig::Setting &translation = fileconfigTranslation["translation"];
        try {
            translationX = translation["x"];
        } catch (const libconfig::ConfigException &) {
            try {
                translationX = static_cast<double>(static_cast<int>(translation["x"]));
            } catch (const libconfig::ConfigException &) {
                cerr << "Not found translation in axe X or value incorrect\n";
                ::exit(84);
            }
        }
        try {
            translationY = translation["y"];
        } catch (const libconfig::ConfigException &) {
            try {
                translationY = static_cast<double>(static_cast<int>(translation["y"]));
            } catch (const libconfig::ConfigException &) {
                cerr << "Not found translation in axe Y or value incorrect\n";
                ::exit(84);
            }
        }
        try {
            translationZ = translation["z"];
        } catch (const libconfig::ConfigException &) {
            try {
                translationZ = static_cast<double>(static_cast<int>(translation["z"]));
            } catch (const libconfig::ConfigException &) {
                cerr << "Not found translation in axe Z or value incorrect\n";
                ::exit(84);
            }
        }
        allMatrix["translation"] = {
            {1.0, 0.0, 0.0, translationX},
            {0.0, 1.0, 0.0, translationY},
            {0.0, 0.0, 1.0, translationZ},
            {0.0, 0.0, 0.0, 1.0}
        };
    } catch (const libconfig::SettingNotFoundException &) {
    }
}